// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type AccountPermsResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data Perms  `json:"data,optional"` //
}

type Api struct {
	Id        string `json:"id"`                                        //
	Type      int64  `json:"type,options=1|2"`                          //类型：1.模块，2.API
	SortId    int64  `json:"sort_id,range=[0:]"`                        //排序
	ParentId  string `json:"parent_id"`                                 //上级id
	Uri       string `json:"uri,optional"`                              //请求路径
	Method    string `json:"method,options=|GET|POST|PUT|PATCH|DELETE"` //请求方法
	Name      string `json:"name"`                                      //名称
	Remark    string `json:"remark,optional"`                           //备注
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
	Children  []*Api `json:"children,optional"`
}

type ApiIdRequest struct {
	Id string `form:"id"`
}

type ApiRequest struct {
	Id       string `json:"id,optional" validate:"omitempty,mongodb" comment:"api"` //
	ParentId string `json:"parent_id"`                                              //上级id
	Type     int64  `json:"type,options=1|2"`                                       //类型：1.模块，2.API
	SortId   int64  `json:"sort_id,range=[0:]"`                                     //排序
	Uri      string `json:"uri,optional"`                                           //请求路径
	Method   string `json:"method,options=|GET|POST|PUT|PATCH|DELETE"`              //请求方法
	Name     string `json:"name"`                                                   //名称
	Remark   string `json:"remark,optional"`                                        //备注
}

type ApisResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data []*Api `json:"data"`
}

type BaseResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type Button struct {
	Name  string `json:"name"`  //按钮名称
	Icon  string `json:"icon"`  //按钮图标
	Perms string `json:"perms"` //按钮权限
}

type Carrier struct {
	Id                            string `json:"id,optional" path:"id"`
	Type                          string `json:"type"`                             //承运商类型：个人、企业、组织
	Code                          string `json:"code"`                             //承运商编号：分配给承运商的唯一标识符或编号，用于快速识别和检索承运商信息
	Name                          string `json:"name"`                             //承运商名称
	Image                         string `json:"image,optional"`                   //承运商图片
	LegalRepresentative           string `json:"legal_representative"`             //法定代表人
	UnifiedSocialCreditIdentifier string `json:"unified_social_credit_identifier"` //统一社会信用代码
	Address                       string `json:"address"`                          //承运商地址
	Contact                       string `json:"contact"`                          //联系方式
	Manager                       string `json:"manager"`                          //负责人
	Email                         string `json:"email"`                            //Email
	Remark                        string `json:"remark"`                           //备注
	Status                        string `json:"status"`                           //状态
	CreateBy                      string `json:"create_by,optional"`               //创建人
	CreatedAt                     int64  `json:"created_at,optional"`
	UpdatedAt                     int64  `json:"updated_at,optional"`
}

type CarrierPaginate struct {
	Total int64     `json:"total"`
	List  []Carrier `json:"list"` //承运商列表
}

type CarrierRequest struct {
	Id                            string `json:"id,optional" validate:"omitempty,mongodb" comment:"承运商"`
	Type                          string `json:"type,optional" validate:"required,oneof=个人 企业 组织" comment:"承运商类型"`                        //供应商类型：个人、企业、组织
	Code                          string `json:"code,optional" validate:"required,gte=6,lte=32" comment:"承运商编号"`                          //承运商编号：分配给承运商的唯一标识符或编号，用于快速识别和检索承运商信息
	Name                          string `json:"name,optional" validate:"required" comment:"承运商名称"`                                       //承运商名称
	Image                         string `json:"image,optional" validate:"omitempty" comment:"承运商图片"`                                     //承运商图片
	LegalRepresentative           string `json:"legal_representative,optional" validate:"required" comment:"法定代表人"`                       //法定代表人
	UnifiedSocialCreditIdentifier string `json:"unified_social_credit_identifier,optional" validate:"required,lte=18" comment:"统一社会信用代码"` //统一社会信用代码
	Address                       string `json:"address,optional" validate:"omitempty" comment:"承运商地址"`                                   //承运商地址
	Contact                       string `json:"contact,optional" validate:"required,mobile" comment:"联系方式"`                              //联系方式
	Manager                       string `json:"manager,optional" validate:"required" comment:"负责人"`                                      //负责人
	Email                         string `json:"email,optional" validate:"omitempty,email" comment:"Email"`                               //Email
	Remark                        string `json:"remark,optional"`
}

type CarrierStatusRequest struct {
	Id     string `json:"id" validate:"required" comment:"承运商"`
	Status string `json:"status" validate:"required,oneof=活跃 停用 暂停合作 终止合作 待审核 审核不通过 审核中 审核通过 资质过期 删除" comment:"状态"` //状态
}

type CarriersRequest struct {
	Page    int64  `form:"page,optional" validate:"required,gte=1" comment:"页数""`
	Size    int64  `form:"size,optional" validate:"required,gte=5,lte=100" comment:"条数"`
	Name    string `form:"name,optional" validate:"omitempty" comment:"承运商名称"`           //承运商名称
	Code    string `form:"code,optional" validate:"omitempty" comment:"承运商编号"`           //承运商编号：分配给承运商的唯一标识符或编号，用于快速识别和检索客户信息
	Manager string `form:"manager,optional" validate:"omitempty" comment:"承运商编号"`        //负责人
	Contact string `form:"contact,optional" validate:"omitempty,mobile" comment:"承运商编号"` //联系方式
	Email   string `form:"email,optional" validate:"omitempty,email" comment:"承运商编号"`    //Email
}

type CarriersResponse struct {
	Code int             `json:"code"`
	Msg  string          `json:"msg"`
	Data CarrierPaginate `json:"data"`
}

type ChangePasswordRequest struct {
	Id       string `json:"id" validate:"mongodb,required" comment:"用户"`
	Password string `json:"password" validate:"required,gte=6" comment:"密码"` //用户密码
}

type Company struct {
	Name                          string `json:"name"`                             //企业名称
	Address                       string `json:"address"`                          //企业地址
	Contact                       string `json:"contact"`                          //联系方式
	LegalRepresentative           string `json:"legal_representative"`             //法定代表人
	UnifiedSocialCreditIdentifier string `json:"unified_social_credit_identifier"` //统一社会信用代码
	Email                         string `json:"email"`                            //Email
	Site                          string `json:"site"`                             //企业网址
	Introduction                  string `json:"introduction"`                     //简介
	BusinessScope                 string `json:"business_scope"`                   //经营范围
	CreatedAt                     int64  `json:"created_at"`                       //
	UpdatedAt                     int64  `json:"updated_at"`                       //
}

type CompanyRequest struct {
	Name                          string `json:"name" validate:"required" comment:"企业名称"`                                 //企业名称
	Address                       string `json:"address" validate:"required" comment:"企业地址"`                              //企业地址
	Contact                       string `json:"contact" validate:"required,mobile" comment:"联系方式"`                       //联系方式
	LegalRepresentative           string `json:"legal_representative" validate:"required" comment:"法定代表人"`                //法定代表人
	UnifiedSocialCreditIdentifier string `json:"unified_social_credit_identifier" validate:"required" comment:"统一社会信用代码"` //统一社会信用代码
	Email                         string `json:"email" validate:"omitempty,email" comment:"Email"`                        //Email
	Site                          string `json:"site" validate:"omitempty,url" comment:"企业网址"`                            //企业网址
	Introduction                  string `json:"introduction" validate:"omitempty" comment:"简介"`                          //简介
	BusinessScope                 string `json:"business_scope" validate:"omitempty" comment:"经营范围"`                      //经营范围
}

type CompanyResponse struct {
	Code int     `json:"code"`
	Msg  string  `json:"msg"`
	Data Company `json:"data,optional"`
}

type Customer struct {
	Id                            string  `json:"id,optional" path:"id"`
	Type                          string  `json:"type"`                             //客户类型：个人、企业、组织
	Code                          string  `json:"code"`                             //客户编号：分配给客户的唯一标识符或编号，用于快速识别和检索客户信息
	Name                          string  `json:"name"`                             //客户名称
	Image                         string  `json:"image,optional"`                   //客户图片
	LegalRepresentative           string  `json:"legal_representative"`             //法定代表人
	UnifiedSocialCreditIdentifier string  `json:"unified_social_credit_identifier"` //统一社会信用代码
	Address                       string  `json:"address"`                          //客户地址
	Contact                       string  `json:"contact"`                          //联系方式
	Manager                       string  `json:"manager"`                          //负责人
	Email                         string  `json:"email"`                            //Email
	Remark                        string  `json:"remark"`                           //备注
	Status                        string  `json:"status"`                           //状态
	ReceivableBalance             float64 `json:"receivable_balance"`               //应收账款
	CreateBy                      string  `json:"create_by,optional"`               //创建人
	CreatedAt                     int64   `json:"created_at,optional"`
	UpdatedAt                     int64   `json:"updated_at,optional"`
}

type CustomerListRequest struct {
	Name    string `form:"name,optional" validate:"omitempty" comment:"客户名称"`           //客户名称
	Code    string `form:"code,optional" validate:"omitempty" comment:"客户编号"`           //客户编号：分配给客户的唯一标识符或编号，用于快速识别和检索客户信息
	Manager string `form:"manager,optional" validate:"omitempty" comment:"负责人"`         //负责人
	Contact string `form:"contact,optional" validate:"omitempty,mobile" comment:"联系方式"` //联系方式
	Email   string `form:"email,optional" validate:"omitempty,email" comment:"Email"`   //Email
}

type CustomerPaginate struct {
	Total int64      `json:"total"`
	List  []Customer `json:"list"` //客户列表
}

type CustomerRequest struct {
	Id                            string  `json:"id,optional" validate:"omitempty,mongodb" comment:"客户"`
	Type                          string  `json:"type,optional" validate:"required,oneof=个人 企业 组织" comment:"客户类型"`                         //供应商类型：个人、企业、组织
	Code                          string  `json:"code,optional" validate:"required,gte=6,lte=32" comment:"客户编号"`                           //客户编号：分配给客户的唯一标识符或编号，用于快速识别和检索客户信息
	Name                          string  `json:"name,optional" validate:"required" comment:"客户名称"`                                        //客户名称
	Image                         string  `json:"image,optional" validate:"omitempty" comment:"客户图片"`                                      //客户图片
	LegalRepresentative           string  `json:"legal_representative,optional" validate:"required" comment:"法定代表人"`                       //法定代表人
	UnifiedSocialCreditIdentifier string  `json:"unified_social_credit_identifier,optional" validate:"required,lte=18" comment:"统一社会信用代码"` //统一社会信用代码
	Address                       string  `json:"address,optional" validate:"omitempty" comment:"客户地址"`                                    //客户地址
	Contact                       string  `json:"contact,optional" validate:"required,mobile" comment:"联系方式"`                              //联系方式
	Manager                       string  `json:"manager,optional" validate:"required" comment:"负责人"`                                      //负责人
	Email                         string  `json:"email,optional" validate:"omitempty,email" comment:"Email"`                               //Email
	Remark                        string  `json:"remark,optional" validate:"omitempty" comment:"备注"`
	ReceivableBalance             float64 `json:"receivable_balance,optional" validate:"omitempty,gte=0" comment:"应收账款"` //应收账款
}

type CustomerStatusRequest struct {
	Id     string `json:"id" validate:"required" comment:"客户"`
	Status string `json:"status" validate:"required,oneof=潜在 活动 停用 冻结 黑名单 合同到期 删除" comment:"状态"` //状态
}

type CustomerTransaction struct {
	Type   string  `json:"type"`   //交易类型：应收账款、回款、退货
	Time   int64   `json:"time"`   //交易时间
	Amount float64 `json:"amount"` //交易金额
	Remark string  `json:"remark"` //备注
	Annex  string  `json:"annex"`  //附件
}

type CustomerTransactionAddRequest struct {
	CustomerId string   `json:"customer_id,optional" validate:"required,mongodb" comment:"客户"`
	Time       int64    `json:"time,optional" validate:"required,gt=0" comment:"交易时间"`             //交易时间
	Type       string   `json:"type,optional" validate:"required,oneof=应收账款 回款 退货" comment:"交易类型"` //交易类型：应收账款、回款、退货
	Amount     float64  `json:"amount,optional" validate:"required,gt=0" comment:"交易金额"`           //交易金额
	Annex      []string `json:"annex,optional" validate:"omitempty,dive,gt=3" comment:"附件"`        //附件
	Remark     string   `json:"remark,optional" validate:"omitempty" comment:"备注"`                 //备注
}

type CustomerTransactionPageRequest struct {
	Page       int64  `form:"page,optional" validate:"required,gte=1" comment:"页数""`
	Size       int64  `form:"size,optional" validate:"required,gte=5,lte=100" comment:"条数"`
	CustomerId string `form:"customer_id,optional" validate:"required,mongodb" comment:"客户"`
}

type CustomerTransactionPaginate struct {
	Total int64                 `json:"total"` //交易流水条数
	List  []CustomerTransaction `json:"list"`  //客户交易流水列表
}

type CustomerTransactionsResponse struct {
	Code int                         `json:"code"`
	Msg  string                      `json:"msg"`
	Data CustomerTransactionPaginate `json:"data"`
}

type CustomersRequest struct {
	Page    int64  `form:"page,optional" validate:"required,gte=1" comment:"页数""`
	Size    int64  `form:"size,optional" validate:"required,gte=5,lte=100" comment:"条数"`
	Name    string `form:"name,optional" validate:"omitempty" comment:"客户名称"`           //客户名称
	Code    string `form:"code,optional" validate:"omitempty" comment:"客户编号"`           //客户编号：分配给客户的唯一标识符或编号，用于快速识别和检索客户信息
	Manager string `form:"manager,optional" validate:"omitempty" comment:"负责人"`         //负责人
	Contact string `form:"contact,optional" validate:"omitempty,mobile" comment:"联系方式"` //联系方式
	Email   string `form:"email,optional" validate:"omitempty,email" comment:"Email"`   //Email
}

type CustomersResponse struct {
	Code int              `json:"code"`
	Msg  string           `json:"msg"`
	Data CustomerPaginate `json:"data"`
}

type Department struct {
	Id        string        `json:"id,optional" path:"id"`
	SortId    int64         `json:"sort_id"`            //排序
	ParentId  string        `json:"parent_id,optional"` //上级部门
	Name      string        `json:"name"`               //部门名称
	Code      string        `json:"code"`               //部门编码
	Remark    string        `json:"remark"`             //备注
	CreatedAt int64         `json:"created_at,optional"`
	UpdatedAt int64         `json:"updated_at,optional"`
	Children  []*Department `json:"children"`
}

type DepartmentRemoveRequest struct {
	Id string `form:"id"`
}

type DepartmentRequest struct {
	Id        string `json:"id,optional"`
	SortId    int64  `json:"sort_id"`            //排序
	ParentId  string `json:"parent_id,optional"` //上级部门
	Name      string `json:"name"`               //部门名称
	Code      string `json:"code"`               //部门编码
	Remark    string `json:"remark"`             //备注
	CreatedAt int64  `json:"created_at,optional"`
	UpdatedAt int64  `json:"updated_at,optional"`
}

type DepartmentResponse struct {
	Code int        `json:"code"`
	Msg  string     `json:"msg"`
	Data Department `json:"data,optional"`
}

type DepartmentsResponse struct {
	Code int           `json:"code"`
	Msg  string        `json:"msg"`
	Data []*Department `json:"data"` //部门列表
}

type ImageItem struct {
	Url string `json:"url"`
	Alt string `json:"alt"`
}

type ImagePaginate struct {
	Total int64       `json:"total"`
	List  []ImageItem `json:"list"` //图片列表
}

type ImageRemoveRequest struct {
	Key string `form:"key,optional" validate:"required" comment:"图片链接"`
}

type ImageResponse struct {
	Code int      `json:"code"`
	Msg  string   `json:"msg"`
	Data ImageUrl `json:"data,optional"`
}

type ImageUrl struct {
	Url string `json:"url"`
}

type ImagesRequest struct {
	Page int64  `form:"page,optional" validate:"required,gte=1" comment:"页数""`
	Size int64  `form:"size,optional" validate:"required,gte=5,lte=100" comment:"条数"`
	Name string `form:"name,optional" validate:"omitempty,lte=20" comment:"图片名称"`
}

type ImagesResponse struct {
	Code int           `json:"code"`
	Msg  string        `json:"msg"`
	Data ImagePaginate `json:"data"`
}

type InboundMaterial struct {
	Index             int      `json:"index" validate:"required,gte=0" comment:"物料顺序"`                               //物料顺序
	Id                string   `json:"id,optional" validate:"required,mongodb" comment:"物料"`                         //物料id
	Price             float64  `json:"price,optional" validate:"number,gte=0" comment:"单价"`                          //单价
	EstimatedQuantity float64  `json:"estimated_quantity,optional" validate:"required,number,gt=0" comment:"预计入库数量"` //预计入库数量
	Position          []string `json:"position,optional" validate:"omitempty,dive,mongodb" comment:"仓储位置id"`         //仓储位置id
}

type InboundMaterialItem struct {
	Index             int     `json:"index"`                       //物料顺序
	Id                string  `json:"id,optional"`                 //物料id
	Name              string  `json:"name,optional"`               //物料名称
	Model             string  `json:"model,optional"`              //物料型号
	Unit              string  `json:"unit,optional"`               //物料单位
	Price             float64 `json:"price,optional"`              //单价
	EstimatedQuantity float64 `json:"estimated_quantity,optional"` //预计入库数量
	ActualQuantity    float64 `json:"actual_quantity,optional"`    //实际入库数量
	Status            string  `json:"status,optional"`             //入库单状态
	CreatorName       string  `json:"creator_name,optional"`       //创建人
	EditorName        string  `json:"editor_name,optional"`        //修改人
	CreatedAt         int64   `json:"created_at,optional"`         //
	UpdatedAt         int64   `json:"updated_at,optional"`         //
}

type InboundReceipt struct {
	Id            string                `json:"id"`
	Code          string                `json:"code,optional"`  //入库单号
	Status        string                `json:"status"`         //入库单状态
	Type          string                `json:"type"`           //入库单类型
	SupplierId    string                `json:"supplier_id"`    //供应商
	SupplierName  string                `json:"supplier_name"`  //供应商名称
	CustomerId    string                `json:"customer_id"`    //客户
	CustomerName  string                `json:"customer_name"`  //客户名称
	ReceivingDate int64                 `json:"receiving_date"` //入库日期
	TotalAmount   float64               `json:"total_amount"`   //总金额
	Materials     []InboundMaterialItem `json:"materials"`      //物料
	Annex         []string              `json:"annex,optional"` //附件
	Remark        string                `json:"remark,optional"`
}

type InboundReceiptAddRequest struct {
	Id            string            `json:"id,optional" validate:"omitempty,mongodb" comment:"入库单"`
	Code          string            `json:"code,optional" validate:"required" comment:"入库单号"`                                      //入库单号
	Type          string            `json:"type,optional" validate:"required,oneof=采购入库 外协入库 生产入库 退货入库" comment:"入库单类型"`           //入库单类型
	SupplierId    string            `json:"supplier_id,optional" validate:"excluded_if=type 退货入库,omitempty,mongodb" comment:"供应商"` //供应商
	CustomerId    string            `json:"customer_id,optional" validate:"required_if=type 退货入库,omitempty,mongodb" comment:"客户"`  //供应商
	TotalAmount   float64           `json:"total_amount,optional" validate:"omitempty,gte=0" comment:"总金额"`                        //总金额
	ReceivingDate int64             `json:"receiving_date,optional" validate:"omitempty,gte=0" comment:"入库日期"`                     //入库日期
	Materials     []InboundMaterial `json:"materials,optional" validate:"required,gt=0,dive" comment:"物料"`                         //物料
	Annex         []string          `json:"annex,optional" validate:"omitempty,dive,gt=3" comment:"附件"`                            //附件
	Remark        string            `json:"remark,optional" validate:"omitempty" comment:"备注"`                                     //备注
}

type InboundReceiptCheckRequest struct {
	Id     string `json:"id,optional" validate:"required,mongodb" comment:"入库单"`                //入库单id
	Status string `json:"status,optional" validate:"required,oneof=审核不通过 审核通过" comment:"入库单状态"` //入库单状态
}

type InboundReceiptIdRequest struct {
	Id string `form:"id,optional" validate:"required,mongodb" comment:"入库单"` //入库单id
}

type InboundReceiptPaginate struct {
	Total int64            `json:"total"`
	List  []InboundReceipt `json:"list"` //入库单列表
}

type InboundReceiptReceiveRequest struct {
	Id            string            `json:"id,optional" validate:"required,mongodb" comment:"入库单"`
	Code          string            `json:"code,optional" validate:"required" comment:"批次入库编号"`                  //批次入库编号
	ReceivingDate int64             `json:"receiving_date,optional" validate:"omitempty,gte=0" comment:"批次入库日期"` //批次入库日期
	CarrierId     string            `json:"carrier_id" validate:"omitempty,mongodb" comment:"承运商"`               //承运商id
	CarrierCost   float64           `json:"carrier_cost" validate:"omitempty,gte=0" comment:"运费"`                //运费
	OtherCost     float64           `json:"other_cost" validate:"omitempty,gte=0" comment:"其他费用"`                //其他费用
	Materials     []InboundReceived `json:"materials,optional" validate:"omitempty,gt=0,dive" comment:"物料"`      //批次入库物料
	Remark        string            `json:"remark,optional" validate:"omitempty,lte=128" comment:"备注"`           //备注
}

type InboundReceiptUpdateRequest struct {
	Id            string            `json:"id,optional" validate:"omitempty,mongodb" comment:"入库单"`
	Code          string            `json:"code,optional" validate:"required" comment:"入库单号"`                                      //入库单号
	Type          string            `json:"type,optional" validate:"required,oneof=采购入库 外协入库 生产入库 退货入库" comment:"入库单类型"`           //入库单类型
	SupplierId    string            `json:"supplier_id,optional" validate:"excluded_if=type 退货入库,omitempty,mongodb" comment:"供应商"` //供应商
	CustomerId    string            `json:"customer_id,optional" validate:"required_if=type 退货入库,omitempty,mongodb" comment:"客户"`  //供应商
	TotalAmount   float64           `json:"total_amount,optional" validate:"omitempty,gte=0" comment:"总金额"`                        //总金额
	ReceivingDate int64             `json:"receiving_date,optional" validate:"omitempty,gte=0" comment:"预计入库日期"`                   //预计入库日期
	Materials     []InboundMaterial `json:"materials,optional" validate:"required,gt=0,dive" comment:"物料"`                         //物料
	Annex         []string          `json:"annex,optional" validate:"omitempty,dive,gt=3" comment:"附件"`                            //附件
	Remark        string            `json:"remark,optional" validate:"omitempty" comment:"备注"`                                     //备注
}

type InboundReceiptsRequest struct {
	Page       int64  `form:"page,optional" validate:"required,gte=1" comment:"页数""`
	Size       int64  `form:"size,optional" validate:"required,gte=5,lte=100" comment:"条数"`
	Code       string `form:"code,optional" validate:"omitempty" comment:"入库单号"`                                             //入库单号
	Status     string `form:"status,optional" validate:"omitempty,oneof=待审核 审核不通过 审核通过 未发货 在途 部分入库 作废 入库完成" comment:"入库单状态"` //入库单状态
	Type       string `form:"type,optional" validate:"omitempty,oneof=采购入库 外协入库 生产入库 退货入库" comment:"入库单类型"`                  //入库单类型
	SupplierId string `form:"supplier_id,optional" validate:"omitempty,mongodb" comment:"供应商"`                               //供应商
	CustomerId string `form:"customer_id,optional" validate:"omitempty,mongodb" comment:"客户"`                                //客户
}

type InboundReceiptsResponse struct {
	Code int                    `json:"code"`
	Msg  string                 `json:"msg"`
	Data InboundReceiptPaginate `json:"data"`
}

type InboundReceiveMaterial struct {
	Id                string  `json:"id"`                  //物料id
	Index             int     `json:"index"`               //物料顺序
	Price             float64 `json:"price"`               //物料单价
	Name              string  `json:"name"`                //物料名称：包括型号、材质、规格、表面处理、强度等级等
	Model             string  `json:"model"`               //型号：用于唯一标识和区分不同种类的钢材。
	Unit              string  `json:"unit"`                //计量单位
	ActualQuantity    float64 `json:"actual_quantity"`     //实际入库数量
	Status            string  `json:"status"`              //物料状态
	WarehouseName     string  `json:"warehouse_name"`      //仓库名称
	WarehouseZoneName string  `json:"warehouse_zone_name"` //库区名称
	WarehouseRackName string  `json:"warehouse_rack_name"` //货架名称
	WarehouseBinName  string  `json:"warehouse_bin_name"`  //货位名称
}

type InboundReceived struct {
	Index          int      `json:"index,optional" validate:"required,gte=0" comment:"物料顺序"`                      //物料顺序
	Id             string   `json:"id,optional" validate:"required,mongodb" comment:"物料"`                         //物料id
	Price          float64  `json:"price,optional" validate:"number,gte=0" comment:"单价"`                          //单价
	ActualQuantity float64  `json:"actual_quantity,optional" validate:"number,gte=0" comment:"实际入库数量"`            //实际入库数量
	Position       []string `json:"position,optional" validate:"omitempty,dive,mongodb" comment:"仓储位置id"`         //仓储位置id
	Status         string   `json:"status,optional" validate:"required,oneof=未发货 在途 部分入库 作废 入库完成" comment:"物料状态"` //物料状态
}

type InboundReceivedRecord struct {
	Id               string                   `json:"id"`                 //入库记录id
	InboundReceiptId string                   `json:"inbound_receipt_id"` //入库单id
	Code             string                   `json:"code"`               //批次入库编号
	CarrierName      string                   `json:"carrier_name"`       //承运商名称
	CarrierCost      float64                  `json:"carrier_cost"`       //运费
	OtherCost        float64                  `json:"other_cost"`         //其他费用
	TotalAmount      float64                  `json:"total_amount"`       //批次入库物料总金额
	ReceivingDate    int64                    `json:"receiving_date"`     //入库日期
	Materials        []InboundReceiveMaterial `json:"materials"`          //批次入库物料清单
	Annex            []string                 `json:"annex"`              //附件
	Remark           string                   `json:"remark"`             //备注
	CreatorId        string                   `json:"creator_id"`         //创建人id
	CreatorName      string                   `json:"creator_name"`       //创建人名称
	CreatedAt        int64                    `json:"created_at"`
}

type InboundReceivedRecordsRequest struct {
	InboundReceiptId string `form:"inbound_receipt_id,optional" validate:"required,mongodb" comment:"入库单"`
}

type InboundReceivedRecordsResponse struct {
	Code int                     `json:"code"`
	Msg  string                  `json:"msg"`
	Data []InboundReceivedRecord `json:"data"`
}

type InventoryItem struct {
	Id                string  `json:"id"`
	Type              string  `json:"type"`
	EntryTime         int64   `json:"entry_time"`          //入库时间
	WarehouseId       string  `json:"warehouse_id"`        //仓库id
	WarehouseName     string  `json:"warehouse_name"`      //仓库名称
	WarehouseZoneId   string  `json:"warehouse_zone_id"`   //库区id
	WarehouseZoneName string  `json:"warehouse_zone_name"` //库区名称
	WarehouseRackId   string  `json:"warehouse_rack_id"`   //货架id
	WarehouseRackName string  `json:"warehouse_rack_name"` //货架名称
	WarehouseBinId    string  `json:"warehouse_bin_id"`    //货位id
	WarehouseBinName  string  `json:"warehouse_bin_name"`  //货位名称
	ReceiptCode       string  `json:"receipt_code"`        //入库单编号
	ReceiveCode       string  `json:"receive_code"`        //批次入库编号
	MaterialId        string  `json:"material_id"`         //物料id
	Name              string  `json:"name"`                //物料名称：包括型号、材质、规格、表面处理、强度等级等
	Price             float64 `json:"price"`               //物料单价
	Model             string  `json:"model"`               //型号：用于唯一标识和区分不同种类的钢材。
	Unit              string  `json:"unit"`                //计量单位
	Quantity          float64 `json:"quantity"`            //库存数量
	AvailableQuantity float64 `json:"available_quantity"`  //可用库存数量
	LockedQuantity    float64 `json:"locked_quantity"`     //锁定库存数量
	FrozenQuantity    float64 `json:"frozen_quantity"`     //冻结库存数量
	CreatorId         string  `json:"creator_id"`          //创建人id
	CreatorName       string  `json:"creator_name"`        //创建人名称
	CreatedAt         int64   `json:"created_at"`
}

type InventoryListRequest struct {
	MaterialId string `form:"material_id,optional" validate:"required,mongodb" comment:"物料id"`
}

type InventoryListResponse struct {
	Code int             `json:"code"`
	Msg  string          `json:"msg"`
	Data []InventoryItem `json:"data"` //入库单列表
}

type InventoryPaginate struct {
	Total    int64           `json:"total"`    //入库记录数
	Quantity float64         `json:"quantity"` //库存总数量
	List     []InventoryItem `json:"list"`     //入库单列表
}

type InventorysRequest struct {
	Page            int64  `form:"page,optional" validate:"required,gte=1" comment:"页数""`
	Size            int64  `form:"size,optional" validate:"required,gte=5,lte=100" comment:"条数"`
	Type            string `form:"type,optional" validate:"omitempty,oneof=采购入库 外协入库 生产入库 退货入库" comment:"入库单类型"` //入库单类型
	MaterialName    string `form:"material_name,optional" validate:"omitempty" comment:"物料名称"`
	MaterialModel   string `form:"material_model,optional" validate:"omitempty" comment:"物料型号"`
	WarehouseId     string `form:"warehouse_id,optional" validate:"omitempty,mongodb" comment:"仓库"`      //仓库Id
	WarehouseZoneId string `form:"warehouse_zone_id,optional" validate:"omitempty,mongodb" comment:"库区"` //库区Id
	WarehouseRackId string `form:"warehouse_rack_id,optional" validate:"omitempty,mongodb" comment:"货架"` //货架Id
	WarehouseBinId  string `form:"warehouse_bin_id,optional" validate:"omitempty,mongodb" comment:"货位"`  //货架Id
}

type InventorysResponse struct {
	Code int               `json:"code"`
	Msg  string            `json:"msg"`
	Data InventoryPaginate `json:"data"`
}

type LoginData struct {
	Name           string `json:"name"`            //账号名称
	Avatar         string `json:"avatar"`          //头像
	Mobile         string `json:"mobile"`          //注册手机号码
	Email          string `json:"email"`           //注册手机号码
	DepartmentId   string `json:"department_id"`   //部门id
	DepartmentName string `json:"department_name"` //部门名称
	Token          string `json:"token"`           //
	Exp            int64  `json:"exp"`             //过期时间戳
}

type LoginRequest struct {
	Mobile   string `json:"mobile,optional" validate:"required,mobile" comment:"手机号码"` //手机号码
	Password string `json:"password,optional" validate:"required,gte=6" comment:"密码"`  //账号密码
}

type LoginResponse struct {
	Code int       `json:"code"`
	Msg  string    `json:"msg"`
	Data LoginData `json:"data,optional"`
}

type Material struct {
	Id               string          `json:"id,optional"`
	Image            string          `json:"image"`             //物料图片
	CategoryId       string          `json:"category_id"`       //物料分类Id
	CategoryName     string          `json:"category_name"`     //物料分类名称
	Name             string          `json:"name"`              //物料名称
	Material         string          `json:"material"`          //材质：碳钢、不锈钢、合金钢等。
	Specification    string          `json:"specification"`     //规格：包括长度、宽度、厚度等尺寸信息。
	Model            string          `json:"model"`             //型号：用于唯一标识和区分不同种类的钢材。
	SurfaceTreatment string          `json:"surface_treatment"` //表面处理。钢材经过的表面处理方式，如热镀锌、喷涂等。
	StrengthGrade    string          `json:"strength_grade"`    //强度等级：钢材的强度等级，常见的钢材强度等级：Q235、Q345
	Quantity         float64         `json:"quantity"`          //安全库存
	Unit             string          `json:"unit"`              //计量单位，如个、箱、千克等
	Remark           string          `json:"remark"`            //备注
	Prices           []MaterialPrice `json:"prices"`            //单价列表
	Creator          string          `json:"creator"`           //
	CreatorName      string          `json:"creator_name"`      //
	CreatedAt        int64           `json:"created_at"`
	UpdatedAt        int64           `json:"updated_at"`
}

type MaterialCategory struct {
	Id          string              `json:"id"`                    //
	ParentId    string              `json:"parent_id"`             //上级物料分类id
	SortId      int64               `json:"sort_id"`               //排序
	Name        string              `json:"name"`                  //物料分类名称
	Status      string              `json:"status"`                //状态：启用、停用
	Remark      string              `json:"remark"`                //备注
	CreatorName string              `json:"creator_name,optional"` //创建人
	CreatedAt   int64               `json:"created_at"`            //
	UpdatedAt   int64               `json:"updated_at"`            //
	Children    []*MaterialCategory `json:"children,optional"`     //
}

type MaterialCategoryIdRequest struct {
	Id string `form:"id"` //物料分类id
}

type MaterialCategoryListResponse struct {
	Code int                 `json:"code"`
	Msg  string              `json:"msg"`
	Data []*MaterialCategory `json:"data,optional"`
}

type MaterialCategoryRequest struct {
	Id       string `json:"id,optional" validate:"omitempty,mongodb" comment:"物料分类Id"`
	ParentId string `json:"parent_id,optional" validate:"omitempty,mongodb" comment:"上级物料分类Id"` //上级物料分类Id
	SortId   int64  `json:"sort_id,optional" validate:"required,gte=0" comment:"排序"`            //排序
	Name     string `json:"name" validate:"required,gte=1,lte=21" comment:"物料分类名称"`             //账号名称
	Status   string `json:"status,optional" validate:"oneof=启用 停用" comment:"状态"`                //用户状态：启用，禁用，删除
	Remark   string `json:"remark,optional" validate:"omitempty,gte=1" comment:"备注"`            //备注
}

type MaterialIdRequest struct {
	Id string `form:"id" validate:"required,mongodb" comment:"物料"`
}

type MaterialPaginate struct {
	Total int64      `json:"total"`
	List  []Material `json:"list"` //物料列表
}

type MaterialPrice struct {
	Price        float64 `json:"price"`         //价格
	Since        int64   `json:"since"`         //价格应用时间
	CustomerId   string  `json:"customer_id"`   //客户id
	CustomerName string  `json:"customer_name"` //客户
}

type MaterialPriceRequest struct {
	Id         string  `form:"id,optional" validate:"required,mongodb" comment:"物料"`          //物料id
	CustomerId string  `form:"customer_id,optional" validate:"required,mongodb" comment:"客户"` //客户id
	Price      float64 `form:"price,optional" validate:"number" comment:"单价"`
}

type MaterialPricesRequest struct {
	MaterialId string `form:"material_id" validate:"required,mongodb" comment:"物料"`           //物料id
	CustomerId string `form:"customer_id,optional" validate:"omitempty,mongodb" comment:"客户"` //客户id
}

type MaterialPricesResponse struct {
	Code int             `json:"code"`
	Msg  string          `json:"msg"`
	Data []MaterialPrice `json:"data"`
}

type MaterialRequest struct {
	Id               string  `json:"id,optional" validate:"omitempty,mongodb" comment:"物料"`
	CategoryId       string  `json:"category_id,optional" validate:"omitempty,mongodb" comment:"物料分类"` //物料分类
	Name             string  `json:"name,optional" validate:"required" comment:"物料名称"`                 //物料名称
	Model            string  `json:"model" validate:"required" comment:"型号"`                           //型号：用于唯一标识和区分不同种类的钢材。
	Image            string  `json:"image,optional" validate:"omitempty" comment:"物料图片"`               //物料图片
	Material         string  `json:"material" validate:"omitempty" comment:"材质"`                       //材质：碳钢、不锈钢、合金钢等。
	Specification    string  `json:"specification,optional" validate:"omitempty" commment:"规格"`        //规格：包括长度、宽度、厚度等尺寸信息。
	SurfaceTreatment string  `json:"surface_treatment" validate:"omitempty" comment:"表面处理"`            //表面处理。钢材经过的表面处理方式，如热镀锌、喷涂等。
	StrengthGrade    string  `json:"strength_grade" validate:"omitempty" comment:"强度等级"`               //强度等级：钢材的强度等级，常见的钢材强度等级：Q235、Q345
	Quantity         float64 `json:"quantity" validate:"gte=0" comment:"安全库存"`                         //安全库存
	Unit             string  `json:"unit,optional" validate:"omitempty" commment:"计量单位"`               //计量单位
	Remark           string  `json:"remark,optional" validate:"omitempty" comment:"备注"`                //备注
	Price            float64 `json:"price,optional" validate:"omitempty,gte=0" comment:"单价"`           //单价
}

type MaterialResponse struct {
	Code int      `json:"code"`
	Msg  string   `json:"msg"`
	Data Material `json:"data"`
}

type MaterialsRequest struct {
	Page             int64  `form:"page,optional" validate:"required,gte=1" comment:"页数""`
	Size             int64  `form:"size,optional" validate:"required,gte=5,lte=100" comment:"条数"`
	Name             string `form:"name,optional" validate:"omitempty" comment:"物料名称"`                //物料名称
	CategoryId       string `form:"category_id,optional" validate:"omitempty,mongodb" comment:"物料分类"` //物料分类
	Material         string `form:"material,optional" validate:"omitempty" comment:"材质"`              //材质：碳钢、不锈钢、合金钢等。
	Specification    string `form:"specification,optional" validate:"omitempty" comment:"规格"`         //规格：包括长度、宽度、厚度等尺寸信息。
	Model            string `form:"model,optional" validate:"omitempty" comment:"型号"`                 //型号：用于唯一标识和区分不同种类的钢材。
	SurfaceTreatment string `form:"surface_treatment,optional" validate:"omitempty" comment:"表面处理"`   //表面处理。钢材经过的表面处理方式，如热镀锌、喷涂等。
	StrengthGrade    string `form:"strength_grade,optional" validate:"omitempty" comment:"强度等级"`      //强度等级：钢材的强度等级，常见的钢材强度等级：Q235、Q345
}

type MaterialsResponse struct {
	Code int              `json:"code"`
	Msg  string           `json:"msg"`
	Data MaterialPaginate `json:"data"`
}

type Menu struct {
	Id        string    `json:"id"`
	Type      int64     `json:"type"`               //路由类型：1.菜单，2.按钮
	SortId    int64     `json:"sort_id"`            //排序
	ParentId  string    `json:"parent_id"`          //父路由id
	Path      string    `json:"path,optional"`      //路由路径
	Name      string    `json:"name,optional"`      //路由名称
	Component string    `json:"component,optional"` //路由组件
	Meta      MetaProps `json:"meta"`
	Remark    string    `json:"remark"` //备注
	CreatedAt int64     `json:"created_at,optional"`
	UpdatedAt int64     `json:"updated_at,optional"`
	Children  []*Menu   `json:"children,optional"`
}

type MenuRemoveRequest struct {
	Id string `form:"id"`
}

type MenuRequest struct {
	Id         string `json:"id,optional" validate:"omitempty,mongodb" comment:"路由Id"`
	Type       int64  `json:"type,options=1|2"`   //路由类型：1.菜单，2.按钮
	SortId     int64  `json:"sort_id"`            //排序
	ParentId   string `json:"parent_id"`          //父路由id
	Path       string `json:"path,optional"`      //路由路径
	Name       string `json:"name,optional"`      //路由名称：如，System
	Component  string `json:"component,optional"` //路由组件
	Icon       string `json:"icon"`               //图标
	Transition string `json:"transition"`         //过渡动画
	Hidden     bool   `json:"hidden"`             //是否隐藏
	Fixed      bool   `json:"fixed"`              //是否固定
	IsFull     bool   `json:"is_full"`            //是否全屏
	Perms      string `json:"perms,optional"`     //权限标识
	Remark     string `json:"remark"`             //备注
}

type MenusResponse struct {
	Code int     `json:"code"`
	Msg  string  `json:"msg"`
	Data []*Menu `json:"data,optional"`
}

type MetaProps struct {
	Title      string `json:"title,optional"` //路由标题
	Icon       string `json:"icon"`           //元信息：图标
	Transition string `json:"transition"`     //元信息：过渡动画
	Hidden     bool   `json:"hidden"`         //元信息：是否隐藏
	Fixed      bool   `json:"fixed"`          //元信息：是否固定
	IsFull     bool   `json:"is_full"`        //元信息：是否全屏
	Perms      string `json:"perms,optional"` //权限标识
}

type OutboundConfirmMaterial struct {
	MaterialId string                             `json:"material_id,optional" validate:"required,mongodb" comment:"物料"` //物料id
	Index      int                                `json:"index,optional" validate:"required,gt=0" comment:"物料序号"`        //物料序号
	Inventorys []OutboundConfirmMaterialInventory `json:"inventorys,optional" validate:"required,dive" comment:"库存列表"`
}

type OutboundConfirmMaterialInventory struct {
	InventoryId      string  `json:"inventory_id,optional" validate:"required,mongodb" comment:"库存"`
	ShipmentQuantity float64 `json:"shipment_quantity,optional" validate:"required,number,gt=0" comment:"出货数量"`
}

type OutboundMaterial struct {
	Index      int     `json:"index" validate:"required,gte=0" comment:"物料顺序"`                   //物料顺序
	MaterialId string  `json:"material_id,optional" validate:"required,mongodb" comment:"物料"`    //物料id
	Price      float64 `json:"price,optional" validate:"number,gte=0" comment:"单价"`              //单价
	Quantity   float64 `json:"quantity,optional" validate:"required,number,gt=0" comment:"出库数量"` //出库数量
}

type OutboundMaterialItem struct {
	Index       int     `json:"index"`                 //物料顺序
	Id          string  `json:"id,optional"`           //物料id
	Name        string  `json:"name,optional"`         //物料名称
	Model       string  `json:"model,optional"`        //物料型号
	Unit        string  `json:"unit,optional"`         //物料单位
	Price       float64 `json:"price,optional"`        //单价
	Quantity    float64 `json:"quantity,optional"`     //出库数量
	CreatorName string  `json:"creator_name,optional"` //创建人
	EditorName  string  `json:"editor_name,optional"`  //修改人
	CreatedAt   int64   `json:"created_at,optional"`   //
	UpdatedAt   int64   `json:"updated_at,optional"`   //
}

type OutboundMaterialPrice struct {
	MaterialId string  `json:"material_id,optional" validate:"required,mongodb" comment:"物料"` //物料id
	Price      float64 `json:"price,optional" validate:"number,gte=0" comment:"单价"`           //单价
}

type OutboundMaterialStatus struct {
	Id             string  `json:"id,optional" validate:"required,mongodb" comment:"物料"`              //物料id
	ActualQuantity float64 `json:"actual_quantity,optional" validate:"number,gte=0" comment:"实际出库数量"` //实际出库数量
}

type OutboundOrderAddRequest struct {
	Code          string             `json:"code,optional" validate:"required" comment:"出库单号"`                                                     //出库单号
	Status        string             `json:"status,optional" validate:"omitempty,oneof=  预发货 待拣货 已拣货 待打包 已打包 待称重 已称重 待出库 已出库 已签收" comment:"出库单状态"` //出库单状态
	Type          string             `json:"type,optional" validate:"required,oneof=销售出库 样品出库 退货出库 报废出库 赠品出库 生产用料出库 退货出库 损耗出库" comment:"出库单类型"`    //出库单类型
	SupplierId    string             `json:"supplier_id,optional" validate:"excluded_if=type 退货出库,omitempty,mongodb" comment:"供应商"`                //供应商
	CustomerId    string             `json:"customer_id,optional" validate:"required_if=type 退货出库,omitempty,mongodb" comment:"客户"`                 //供应商
	TotalAmount   float64            `json:"total_amount,optional" validate:"omitempty,gte=0" comment:"总金额"`                                       //总金额
	ReceivingDate int64              `json:"receiving_date,optional" validate:"omitempty,gte=0" comment:"出库日期"`                                    //出库日期
	Materials     []OutboundMaterial `json:"materials,optional" validate:"required,gt=0,dive" comment:"物料"`                                        //物料
	Annex         []string           `json:"annex,optional" validate:"omitempty,dive,gt=3" comment:"附件"`                                           //附件
	Remark        string             `json:"remark,optional" validate:"omitempty" comment:"备注"`                                                    //备注
}

type OutboundOrderConfirmRequest struct {
	Code        string                    `json:"code,optional" validate:"required" comment:"出库单号"`              //出库单号
	ConfirmTime int64                     `json:"confirm_time,optional" validate:"required,gt=0" comment:"确认时间"` //确认时间
	Materials   []OutboundConfirmMaterial `json:"materials,optional" validate:"required,gt=0,dive" comment:"物料"` //物料
}

type OutboundOrderDepartureRequest struct {
	Code          string  `json:"code,optional" validate:"required" comment:"出库单号"`                //出库单号
	DepartureTime int64   `json:"departure_time,optional" validate:"required,gt=0" comment:"出库时间"` //出库时间
	CarrierId     string  `json:"carrier_id,optional" validate:"omitempty,mongodb" comment:"承运商"`  //承运商id
	CarrierCost   float64 `json:"carrier_cost,optional" validate:"omitempty,gte=0" comment:"运费"`   //运费
	OtherCost     float64 `json:"other_cost,optional" validate:"omitempty,gte=0" comment:"其他费用"`   //其他费用
}

type OutboundOrderIdRequest struct {
	Id string `form:"id,optional" validate:"required,mongodb" comment:"出库单"` //出库单id
}

type OutboundOrderItem struct {
	Id            string                  `json:"id"`
	Code          string                  `json:"code,optional"`  //出库单号
	Status        string                  `json:"status"`         //出库单状态
	IsPack        int                     `json:"is_pack"`        //是否打包
	IsWeigh       int                     `json:"is_weigh"`       //是否称重
	Type          string                  `json:"type"`           //出库单类型
	SupplierId    string                  `json:"supplier_id"`    //供应商
	SupplierName  string                  `json:"supplier_name"`  //供应商名称
	CustomerId    string                  `json:"customer_id"`    //客户
	CustomerName  string                  `json:"customer_name"`  //客户名称
	CarrierId     string                  `json:"carrier_id"`     //承运商
	CarrierName   string                  `json:"carrier_name"`   //承运商名称
	CarrierCost   float64                 `json:"carrier_cost"`   //运费
	OtherCost     float64                 `json:"other_cost"`     //其他费用
	ConfirmTime   int64                   `json:"confirm_time"`   //出库单确认时间
	PickingTime   int64                   `json:"picking_time"`   //拣货时间
	PackingTime   int64                   `json:"packing_time"`   //打包时间
	WeighingTime  int64                   `json:"weighing_time"`  //称重时间
	DepartureTime int64                   `json:"departure_time"` //出库时间
	ReceiptTime   int64                   `json:"receipt_time"`   //签收时间
	TotalAmount   float64                 `json:"total_amount"`   //总金额
	Annex         []string                `json:"annex,optional"` //附件
	Remark        string                  `json:"remark,optional"`
	Materials     []OutboundOrderMaterial `json:"materials"` //出库单物料
}

type OutboundOrderMaterial struct {
	Id            string  `json:"id"`            //id
	OrderCode     string  `json:"order_code"`    //物料编号
	MaterialId    string  `json:"material_id"`   //物料id
	Index         int     `json:"index"`         //物料顺序
	Name          string  `json:"name"`          //物料名称
	Model         string  `json:"model"`         //型号
	Specification string  `json:"specification"` //规格
	Price         float64 `json:"price"`         //物料单价
	Quantity      float64 `json:"quantity"`      //出库数量
	Weight        float64 `json:"weight"`        //重量
	Unit          string  `json:"unit"`          //计量单位
}

type OutboundOrderMaterialsRequest struct {
	OrderCode string `form:"order_code,optional" validate:"required" comment:"出库单编号"` //出库单出库单编号
}

type OutboundOrderMaterialsResponse struct {
	Code int                     `json:"code"`
	Msg  string                  `json:"msg"`
	Data []OutboundOrderMaterial `json:"data"`
}

type OutboundOrderPackRequest struct {
	Code        string `json:"code,optional" validate:"required" comment:"出库单号"`              //出库单号
	PackingTime int64  `json:"packing_time,optional" validate:"required,gt=0" comment:"打包时间"` //打包时间
}

type OutboundOrderPaginate struct {
	Total int64               `json:"total"`
	List  []OutboundOrderItem `json:"list"` //出库单列表
}

type OutboundOrderPickRequest struct {
	Code        string `json:"code,optional" validate:"required" comment:"出库单号"`              //出库单号
	PickingTime int64  `json:"picking_time,optional" validate:"required,gt=0" comment:"拣货时间"` //拣货时间
}

type OutboundOrderReceiptRequest struct {
	Code        string   `json:"code,optional" validate:"required" comment:"出库单号"`              //出库单号
	ReceiptTime int64    `json:"receipt_time,optional" validate:"required,gt=0" comment:"签收时间"` //签收时间
	Annex       []string `json:"annex,optional" validate:"required,gte=0" comment:"附件"`         //附件
}

type OutboundOrderRecord struct {
	Code          string `json:"code"`           //出库单号
	DepartureDate int64  `json:"departure_date"` //出库日期
	ReceiptDate   int64  `json:"receipt_date"`   //签收日期
	OutboundOrderMaterial
}

type OutboundOrderReviseRequest struct {
	Code           string                  `json:"code,optional" validate:"required" comment:"出库单号"`              //出库单号
	CustomerId     string                  `json:"customer_id,optional" validate:"required,mongodb" comment:"客户"` //客户
	MaterialsPrice []OutboundMaterialPrice `json:"materials_price,optional" validate:"required,gt=0,dive" comment:"物料单价"`
}

type OutboundOrderWeighRequest struct {
	Code         string                  `json:"code,optional" validate:"required" comment:"出库单号"`                  //出库单号
	WeighingTime int64                   `json:"weighing_time,optional" validate:"required,gt=0" comment:"称重时间"`    //称重时间
	Materials    []OutboundWeighMaterial `json:"materials,optional" validate:"required,gt=0,dive" comment:"称重物料列表"` //称重物料列表
}

type OutboundOrdersRequest struct {
	Page       int64  `form:"page,optional" validate:"required,gte=1" comment:"页数""`
	Size       int64  `form:"size,optional" validate:"required,gte=5,lte=50" comment:"条数"`
	Code       string `form:"code,optional" validate:"omitempty" comment:"出库单号"`                                                    //出库单号
	Status     string `form:"status,optional" validate:"omitempty,oneof=  预发货 待拣货 已拣货 待打包 已打包 待称重 已称重 待出库 已出库 已签收" comment:"出库单状态"` //出库单状态
	IsPack     int    `form:"is_pack,optional" validate:"omitempty,oneof=-1 0 1" comment:"是否打包"`                                    //是否打包：-1忽略，0否,1是
	IsWeigh    int    `form:"is_weigh,optional" validate:"omitempty,oneof=-1 0 1" comment:"是否称重"`                                   //是否称重：-1忽略，0否,1是
	Type       string `form:"type,optional" validate:"omitempty,oneof=销售出库 样品出库 报废出库 赠品出库 生产用料出库 退货出库 损耗出库" comment:"出库单类型"`        //出库单类型
	SupplierId string `form:"supplier_id,optional" validate:"omitempty,mongodb" comment:"供应商"`                                      //供应商
	CustomerId string `form:"customer_id,optional" validate:"omitempty,mongodb" comment:"客户"`                                       //客户
	StartTime  int64  `form:"start_time,optional" validate:"omitempty,gte=0" comment:"签收起始时间"`
	EndTime    int64  `form:"end_time,optional" validate:"omitempty,gte=0" comment:"签收截止时间"`
}

type OutboundOrdersResponse struct {
	Code int                   `json:"code"`
	Msg  string                `json:"msg"`
	Data OutboundOrderPaginate `json:"data"`
}

type OutboundPickingMaterialInventory struct {
	InventoryId      string  `json:"inventory_id,optional" validate:"required,mongodb" comment:"库存"`
	ShipmentQuantity float64 `json:"shipment_quantity,optional" validate:"required,number,gt=0" comment:"出货数量"`
}

type OutboundSummaryRequest struct {
	CustomerId string `form:"customer_id,optional" validate:"required,mongodb" comment:"客户"`      //客户id
	StartDate  int64  `form:"start_date,optional" validate:"required,number,gt=0" comment:"起始日期"` //起始日期
	EndDate    int64  `form:"end_date,optional" validate:"required,number,gt=0" comment:"截止日期"`   //截止日期
}

type OutboundSummaryResponse struct {
	Code int                   `json:"code"`
	Msg  string                `json:"msg"`
	Data []OutboundOrderRecord `json:"data"`
}

type OutboundWeighMaterial struct {
	MaterialId string  `json:"material_id,optional" validate:"required,mongodb" comment:"物料"` //物料id
	Weight     float64 `json:"weight,optional" validate:"gte=0" comment:"物料重量"`               //物料重量
}

type Perms struct {
	Menus   []*Menu  `json:"menus"`
	Buttons []Button `json:"buttons"`
}

type Plan struct {
	Id               string  `json:"id"`
	Type             string  `json:"type"`              //类型
	Status           string  `json:"status"`            //状态
	CustomerId       string  `json:"customer_id"`       //客户id
	CustomerName     string  `json:"customer_name"`     //客户名称
	SupplierId       string  `json:"supplier_id"`       //供应商id
	SupplierName     string  `json:"supplier_name"`     //供应商名称
	MaterialId       string  `json:"material_id"`       //物料id
	MaterialName     string  `json:"material_name"`     //物料名称
	MaterialModel    string  `json:"material_model"`    //物料型号
	MaterialImage    string  `json:"material_image"`    //物料图片
	MaterialUnit     string  `json:"material_unit"`     //物料单位
	MaterialQuantity float64 `json:"material_quantity"` //数量
	Deadline         int64   `json:"deadline,optional"` //截止时间
}

type PlanAddRequest struct {
	Id               string  `json:"id,optional" validate:"omitempty,mongodb" comment:"计划"`
	Type             string  `json:"type,optional" validate:"required,oneof=采购计划 生产计划" comment:"类型"`  //类型
	CustomerId       string  `json:"customer_id,optional" validate:"omitempty,mongodb" comment:"客户"`  //客户id
	SupplierId       string  `json:"supplier_id,optional" validate:"omitempty,mongodb" comment:"供应商"` //供应商id
	MaterialId       string  `json:"material_id,optional" validate:"required,mongodb" comment:"物料"`   //物料id
	MaterialQuantity float64 `json:"material_quantity,optional" validate:"number,gt=0" comment:"数量"`  //数量
	Deadline         int64   `json:"deadline,optional" validate:"required,gte=0" comment:"截止时间"`      //截止时间
}

type PlanIdRequest struct {
	Id string `json:"id,optional" validate:"required,mongodb" comment:"计划"`
}

type PlanPaginate struct {
	Total int64  `json:"total,optional"` //用于返回全部计划时，不可用
	List  []Plan `json:"list"`           //计划分页
}

type PlanStatusRequest struct {
	Id     string `json:"id,optional" validate:"required,mongodb" comment:"计划"`
	Status string `json:"status,optional" validate:"required,oneof=执行中 已完成" comment:"状态"` //状态
}

type PlanUpdateRequest struct {
	Id               string  `json:"id,optional" validate:"omitempty,mongodb" comment:"计划"`
	MaterialQuantity float64 `json:"material_quantity,optional" validate:"number,gt=0" comment:"数量"` //数量
	Deadline         int64   `json:"deadline,optional" validate:"required,gte=0" comment:"截止时间"`     //截止时间
}

type PlansRequest struct {
	Page   int64  `form:"page,optional" validate:"required,gte=1" comment:"页数""`
	Size   int64  `form:"size,optional" validate:"required,gte=5,lte=50" comment:"条数"`
	Status string `form:"status,optional" validate:"omitempty,oneof=执行中 已完成" comment:"状态"` //状态
}

type PlansResponse struct {
	Code int          `json:"code"`
	Msg  string       `json:"msg"`
	Data PlanPaginate `json:"data"`
}

type Profile struct {
	Name           string `json:"name"`            //账号名称
	Sex            string `json:"sex"`             //性别
	DepartmentId   string `json:"department_id"`   //部门id
	DepartmentName string `json:"department_name"` //部门名称
	Mobile         string `json:"mobile,optional"` //手机号码
	Email          string `json:"email,optional"`  //邮箱
	Status         string `json:"status,optional"` //用户状态：启用，禁用，删除
	Avatar         string `json:"avatar"`          //头像
	Remark         string `json:"remark,optional"` //备注
	CreatedAt      int64  `json:"created_at,optional"`
	UpdatedAt      int64  `json:"updated_at,optional"`
}

type ProfileAvatarRequest struct {
	Avatar string `json:"avatar,optional" validate:"url,required" comment:"头像"` //头像链接
}

type ProfilePasswordRequest struct {
	Password string `json:"password,optional" validate:"required,gte=6" comment:"密码"` //用户密码
}

type ProfileRequest struct {
	Name         string   `json:"name"`            //账号名称
	Sex          string   `json:"sex"`             //性别
	DepartmentId string   `json:"department_id"`   //部门id
	RolesId      []string `json:"roles_id"`        //角色id
	Mobile       string   `json:"mobile"`          //手机号码
	Email        string   `json:"email,optional"`  //邮箱
	Remark       string   `json:"remark,optional"` //备注
}

type ProfileResponse struct {
	Code int     `json:"code"`
	Msg  string  `json:"msg"`
	Data Profile `json:"data,optional"`
}

type RegisterRequest struct {
	Company  string `json:"company,optional" validate:"required" comment:"企业名称"`       //公司名称，顶级部门名称
	Name     string `json:"name,optional" validate:"required" comment:"账号名称"`          //账号名称
	Password string `json:"password,optional" validate:"required,gte=6" comment:"密码"`  //账号密码
	Mobile   string `json:"mobile,optional" validate:"required,mobile" comment:"手机号码"` //手机号码
	Email    string `json:"email,optional" validate:"omitempty,email" comment:"Email"` //Email
}

type RegisterResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type Role struct {
	Id        string `json:"id"`
	ParentId  string `json:"parent_id"`         //上级角色id
	Status    string `json:"status,range=(0:]"` //状态：停用，启用，删除
	Name      string `json:"name"`              //角色名称
	Remark    string `json:"remark"`            //备注
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type RoleApisRequest struct {
	Id     string   `json:"id,optional" validate:"required,mongodb" comment:"角色"`                   //角色id
	ApisId []string `json:"apis_id,optional" validate:"required,gte=1,dive,required" comment:"Api"` //api id
}

type RoleApisResponse struct {
	Code int      `json:"code"`
	Msg  string   `json:"msg"`
	Data []string `json:"data"`
}

type RoleIdRequest struct {
	Id string `form:"id" validate:"required" comment:"角色"`
}

type RoleListRequest struct {
	Name string `form:"name,optional" validate:"omitempty" comment:"角色名称"` //角色名称
}

type RoleListResponse struct {
	Code int          `json:"code"`
	Msg  string       `json:"msg"`
	Data RolePaginate `json:"data"`
}

type RoleMenusRequest struct {
	Id      string   `json:"id,optional" validate:"required,mongodb" comment:"角色"`                   //角色id
	MenusId []string `json:"menus_id,optional" validate:"required,gte=1,dive,required" comment:"菜单"` //菜单id
}

type RoleMenusResponse struct {
	Code int      `json:"code"`
	Msg  string   `json:"msg"`
	Data []string `json:"data"`
}

type RolePaginate struct {
	Total int64  `json:"total,optional"` //用于返回全部角色时，不可用
	List  []Role `json:"list"`           //角色分页
}

type RoleRequest struct {
	Id       string `json:"id,optional" validate:"omitempty" comment:"角色"`
	ParentId string `json:"parent_id,optional" validate:"omitempty" comment:"上级角色"`          //上级角色id
	Status   string `json:"status,optional" validate:"required,oneof=启用 禁用 删除" comment:"状态"` //状态：停用，启用，删除
	Name     string `json:"name,optional" validate:"required" comment:"角色名称"`                //角色名称
	Remark   string `json:"remark,optional" validate:"omitempty" comment:"备注"`               //备注
}

type RoleStatusRequest struct {
	Id     []string `json:"id,optional" validate:"required,gte=1,dive,required,mongodb" comment:"角色"`
	Status string   `json:"status,optional" validate:"required,oneof=启用 禁用 删除" comment:"状态"` //状态：停用，启用，删除
}

type RolesRequest struct {
	Page int64  `form:"page" validate:"required,gte=1" comment:"页数"`
	Size int64  `form:"size" validate:"required,gte=1" comment:"条数"`
	Name string `form:"name,optional" validate:"omitempty" comment:"角色名称"` //角色名称
}

type RolesResponse struct {
	Code int          `json:"code"`
	Msg  string       `json:"msg"`
	Data RolePaginate `json:"data"`
}

type Supplier struct {
	Id                            string `json:"id,optional" path:"id"`
	Type                          string `json:"type"`                             //供应商类型：个人、企业、组织
	Name                          string `json:"name"`                             //供应商名称
	Code                          string `json:"code"`                             //供应商编号：分配给供应商的唯一标识符或编号，用于快速识别和检索客户信息
	Image                         string `json:"image,optional"`                   //供应商图片
	LegalRepresentative           string `json:"legal_representative"`             //法定代表人
	UnifiedSocialCreditIdentifier string `json:"unified_social_credit_identifier"` //统一社会信用代码
	Address                       string `json:"address"`                          //供应商地址
	Contact                       string `json:"contact"`                          //联系方式
	Manager                       string `json:"manager"`                          //负责人
	Level                         int    `json:"level"`                            //供应商等级
	Email                         string `json:"email"`                            //Email
	Remark                        string `json:"remark"`                           //备注
	Status                        string `json:"status"`                           //状态：10.启用；100.删除
	CreateBy                      string `json:"create_by,optional"`               //创建人
	CreatedAt                     int64  `json:"created_at,optional"`
	UpdatedAt                     int64  `json:"updated_at,optional"`
}

type SupplierListRequest struct {
	Name    string `form:"name,optional" validate:"omitempty" comment:"供应商名称"`               //供应商名称
	Code    string `form:"code,optional" validate:"omitempty" comment:"供应商编号"`               //供应商编号：分配给供应商的唯一标识符或编号，用于快速识别和检索客户信息
	Manager string `form:"manager,optional" validate:"omitempty" comment:"负责人"`              //负责人
	Contact string `form:"contact,optional" validate:"omitempty,mobile" comment:"联系方式"`      //联系方式
	Email   string `form:"email,optional" validate:"omitempty,email" comment:"Email"`        //Email
	Level   int    `form:"level,optional" validate:"omitempty,gte=1,lte=10" comment:"供应商等级"` //供应商等级
}

type SupplierPaginate struct {
	Total int64      `json:"total"`
	List  []Supplier `json:"list"` //供应商列表
}

type SupplierRequest struct {
	Id                            string `json:"id,optional" validate:"omitempty,mongodb" comment:"供应商"`
	Type                          string `json:"type,optional" validate:"required,oneof=个人 企业 组织" comment:"供应商类型"`                        //供应商类型：个人、企业、组织
	Level                         int    `json:"level,optional" validate:"required,gte=1,lte=10" comment:"供应商等级"`                         //供应商等级
	Code                          string `json:"code,optional" validate:"required,gte=6,lte=32" comment:"供应商编号"`                          //供应商编号：分配给供应商的唯一标识符或编号，用于快速识别和检索客户信息
	Image                         string `json:"image,optional" validate:"omitempty" comment:"供应商图片"`                                     //供应商图片
	Name                          string `json:"name,optional" validate:"required" comment:"供应商名称"`                                       //供应商名称
	LegalRepresentative           string `json:"legal_representative,optional" validate:"required" comment:"法定代表人"`                       //法定代表人
	UnifiedSocialCreditIdentifier string `json:"unified_social_credit_identifier,optional" validate:"required,lte=18" comment:"统一社会信用代码"` //统一社会信用代码
	Contact                       string `json:"contact,optional" validate:"required,mobile" comment:"联系方式"`                              //联系方式
	Manager                       string `json:"manager,optional" validate:"required" comment:"负责人"`                                      //负责人
	Email                         string `json:"email,optional" validate:"omitempty,email" comment:"Email"`                               //Email
	Address                       string `json:"address,optional" validate:"omitempty" comment:"供应商地址"`                                   //供应商地址
	Remark                        string `json:"remark,optional"`                                                                         //备注
}

type SupplierStatusRequest struct {
	Id     string `json:"id" validate:"required" comment:"供应商"`
	Status string `json:"status" validate:"required,oneof=审核中 审核不通过 活动 停用 黑名单 合同到期 删除" comment:"状态"` //状态
}

type SuppliersRequest struct {
	Page    int64  `form:"page,optional" validate:"required,gte=1" comment:"页数""`
	Size    int64  `form:"size,optional" validate:"required,gte=5,lte=100" comment:"条数"`
	Name    string `form:"name,optional" validate:"omitempty" comment:"供应商名称"`               //供应商名称
	Code    string `form:"code,optional" validate:"omitempty" comment:"供应商编号"`               //供应商编号：分配给供应商的唯一标识符或编号，用于快速识别和检索客户信息
	Manager string `form:"manager,optional" validate:"omitempty" comment:"负责人"`              //负责人
	Contact string `form:"contact,optional" validate:"omitempty,mobile" comment:"联系方式"`      //联系方式
	Email   string `form:"email,optional" validate:"omitempty,email" comment:"Email"`        //Email
	Level   int    `form:"level,optional" validate:"omitempty,gte=1,lte=10" comment:"供应商等级"` //供应商等级
}

type SuppliersResponse struct {
	Code int              `json:"code"`
	Msg  string           `json:"msg"`
	Data SupplierPaginate `json:"data"`
}

type User struct {
	Id             string   `json:"id,optional" validate:"omitempty,mongodb" comment:"账号"`
	Name           string   `json:"name" validate:"required" comment:"账号名称"`                       //账号名称
	Sex            string   `json:"sex" validate:"required,oneof=男 女" comment:"性别"`                //性别
	DepartmentId   string   `json:"department_id" validate:"mongodb,required" comment:"部门"`        //部门id
	DepartmentName string   `json:"department_name,optional"`                                      //部门名称
	RolesId        []string `json:"roles_id" validate:"gt=0,dive,required,mongodb" comment:"角色id"` //角色id
	RolesName      []string `json:"roles_name" validate:"gt=0,dive,required" comment:"角色名称"`       //角色名称
	Mobile         string   `json:"mobile,optional" validate:"required,mobile" comment:"手机号码"`     //手机号码
	Email          string   `json:"email,optional"  validate:"omitempty,email" comment:"Email"`    //邮箱
	Status         string   `json:"status,optional" validate:"oneof=启用 禁用 删除" comment:"状态"`        //用户状态：启用，禁用，删除
	Remark         string   `json:"remark,optional" validate:"omitempty,gte=1" comment:"备注"`       //备注
	CreatedAt      int64    `json:"created_at,optional"`
	UpdatedAt      int64    `json:"updated_at,optional"`
}

type UserAddRequest struct {
	Name         string   `json:"name" validate:"required,gte=2,lte=21" comment:"账号名称"`        //账号名称
	Password     string   `json:"password" validate:"required,gte=6" comment:"密码"`             //用户密码
	Sex          string   `json:"sex" validate:"required,oneof=男 女" comment:"性别"`              //性别
	DepartmentId string   `json:"department_id" validate:"mongodb,required" comment:"部门"`      //部门id
	RolesId      []string `json:"roles_id" validate:"gt=0,dive,required,mongodb" comment:"角色"` //角色id
	Mobile       string   `json:"mobile,optional" validate:"required,mobile" comment:"手机号码"`   //手机号码
	Email        string   `json:"email,optional"  validate:"omitempty,email" comment:"Email"`  //邮箱
	Status       string   `json:"status,optional" validate:"oneof=启用" comment:"状态"`            //用户状态：启用
	Remark       string   `json:"remark,optional" validate:"omitempty,gte=1" comment:"备注"`     //备注
}

type UserIdRequest struct {
	Id string `form:"id,optional" validate:"mongodb,required" comment:"用户"`
}

type UserPaginate struct {
	Total int64  `json:"total"`
	List  []User `json:"list"` //用户列表
}

type UserRolesRequest struct {
	Id      string   `json:"id,optional" validate:"omitempty,mongodb" comment:"账号"`
	RolesId []string `json:"roles_id" validate:"required,gt=0,dive,required,mongodb" comment:"角色"` //角色id
}

type UserStatusRequest struct {
	Id     []string `json:"id,optional" validate:"required,gte=1,dive,required,mongodb" comment:"用户"`
	Status string   `json:"status,optional" validate:"oneof=启用 禁用 删除" comment:"状态"` //用户状态：启用，禁用，删除
}

type UserUpdateRequest struct {
	Id           string   `json:"id,optional" validate:"omitempty,mongodb" comment:"账号"`
	Name         string   `json:"name" validate:"required,gte=2,lte=21" comment:"账号名称"`        //账号名称
	Sex          string   `json:"sex" validate:"required,oneof=男 女" comment:"性别"`              //性别
	DepartmentId string   `json:"department_id" validate:"mongodb,required" comment:"部门"`      //部门id
	RolesId      []string `json:"roles_id" validate:"gt=0,dive,required,mongodb" comment:"角色"` //角色id
	Mobile       string   `json:"mobile,optional" validate:"required,mobile" comment:"手机号码"`   //手机号码
	Email        string   `json:"email,optional"  validate:"omitempty,email" comment:"Email"`  //邮箱
	Status       string   `json:"status,optional" validate:"oneof=启用 禁用 删除" comment:"状态"`      //用户状态：启用，禁用，删除
	Remark       string   `json:"remark,optional" validate:"omitempty,gte=1" comment:"备注"`     //备注
}

type UsersRequest struct {
	Page   int64  `form:"page,optional" validate:"required,gte=1" comment:"页数""`
	Size   int64  `form:"size,optional" validate:"required,gte=5,lte=100" comment:"条数"`
	Name   string `form:"name,optional"`   //搜索关键词：用户名
	Mobile string `form:"mobile,optional"` //搜索关键词：手机号码
}

type UsersResponse struct {
	Code int          `json:"code"`
	Msg  string       `json:"msg"`
	Data UserPaginate `json:"data"`
}

type Warehouse struct {
	Id           string  `json:"id,optional"`
	Type         string  `json:"type,optional"`          //仓库类型
	Name         string  `json:"name,optional"`          //仓库名称
	Code         string  `json:"code,optional"`          //仓库编号：分配给客户的唯一标识符或编号，用于快速识别和检索客户信息
	Address      string  `json:"address,optional"`       //仓库地址
	Capacity     float64 `json:"capacity,optional"`      // 仓库容量
	CapacityUnit string  `json:"capacity_unit,optional"` // 仓库容量单位：面积、体积或其他度量单位
	Status       string  `json:"status,optional"`        //仓库状态
	Manager      string  `json:"manager,optional"`       //负责人
	Contact      string  `json:"contact,optional"`       //联系方式
	Image        string  `json:"image,optional"`         //图片
	Remark       string  `json:"remark,optional"`        //备注
	CreateBy     string  `json:"create_by,optional"`     //创建人
	CreatedAt    int64   `json:"created_at"`             //
	UpdatedAt    int64   `json:"updated_at"`             //
}

type WarehouseBin struct {
	Id                string  `json:"id"`
	WarehouseId       string  `json:"warehouse_id,optional"`   //仓库Id
	WarehouseName     string  `json:"warehouse_name,optional"` //仓库名称
	WarehouseZoneId   string  `json:"warehouse_zone_id"`       //库区Id
	WarehouseZoneName string  `json:"warehouse_zone_name"`     //库区名称
	WarehouseRackId   string  `json:"warehouse_rack_id"`       //货架Id
	WarehouseRackName string  `json:"warehouse_rack_name"`     //货架名称
	Name              string  `json:"name"`                    //货位名称
	Code              string  `json:"code"`                    //货位编号：分配给客户的唯一标识符或编号，用于快速识别和检索客户信息
	Image             string  `json:"image"`                   // 货架图片
	Capacity          float64 `json:"capacity"`                // 货位容量
	CapacityUnit      string  `json:"capacity_unit"`           // 货位容量单位：面积、体积或其他度量单位
	Status            string  `json:"status"`                  //货位状态:激活 禁用 盘点中 关闭
	Manager           string  `json:"manager,optional"`        //负责人
	Contact           string  `json:"contact,optional"`        //联系方式
	Remark            string  `json:"remark"`                  //备注
	CreateBy          string  `json:"create_by,optional"`      //创建人
	CreatedAt         int64   `json:"created_at"`              //
	UpdatedAt         int64   `json:"updated_at"`              //
}

type WarehouseBinListRequest struct {
	WarehouseId     string `form:"warehouse_id,optional" validate:"omitempty,mongodb" comment:"仓库"`        //仓库Id
	WarehouseZoneId string `form:"warehouse_zone_id,optional" validate:"omitempty,mongodb" comment:"库区"`   //库区Id
	WarehouseRackId string `form:"warehouse_rack_id,optional" validate:"required,mongodb" comment:"货架"`    //货架Id
	Name            string `form:"name,optional" validate:"omitempty" comment:"货位名称"`                      //货位名称
	Code            string `form:"code,optional" validate:"omitempty" comment:"货位编号"`                      //货位编号：分配给客户的唯一标识符或编号，用于快速识别和检索客户信息
	Status          string `form:"status,optional" validate:"omitempty,oneof=激活 禁用 盘点中 关闭" comment:"货位状态"` //货位状态：不允许查询已删除的数据库
}

type WarehouseBinListResponse struct {
	Code int                  `json:"code"`
	Msg  string               `json:"msg"`
	Data WarehouseBinPaginate `json:"data"`
}

type WarehouseBinPaginate struct {
	Total int64          `json:"total"`
	List  []WarehouseBin `json:"list"` //用户列表
}

type WarehouseBinRequest struct {
	Id              string  `json:"id,optional" validate:"omitempty,mongodb" comment:"货位"`
	WarehouseRackId string  `json:"warehouse_rack_id,optional" validate:"required,mongodb" comment:"货架"` //货架Id
	Name            string  `json:"name,optional" validate:"required" comment:"货位名称"`                    //货位名称
	Code            string  `json:"code,optional" validate:"required" comment:"货位编号"`                    //货位编号：分配给客户的唯一标识符或编号，用于快速识别和检索客户信息
	Image           string  `json:"image" validate:"omitempty" comment:"货架图片"`                           // 货架图片
	Capacity        float64 `json:"capacity,optional" validate:"omitempty,gte=0" comment:"货位容量"`         // 货位容量
	CapacityUnit    string  `json:"capacity_unit,optional" validate:"omitempty" comment:"货位容量单位"`        // 货位容量单位：面积、体积或其他度量单位
	Manager         string  `json:"manager,optional"`                                                    //负责人
	Contact         string  `json:"contact,optional"`                                                    //联系方式
	Remark          string  `json:"remark,optional" validate:"omitempty" comment:"备注"`                   //备注
}

type WarehouseBinStatusRequest struct {
	Id     string `json:"id" validate:"required,mongodb" comment:"货位"`
	Status string `json:"status" validate:"required,oneof=激活 禁用 盘点中 关闭 删除" comment:"货位状态"` //货位状态
}

type WarehouseBinsRequest struct {
	Page            int64  `form:"page,optional" validate:"required,gte=1" comment:"页数""`
	Size            int64  `form:"size,optional" validate:"required,gte=5,lte=100" comment:"条数"`
	WarehouseId     string `form:"warehouse_id,optional" validate:"omitempty,mongodb" comment:"仓库"`        //仓库Id
	WarehouseZoneId string `form:"warehouse_zone_id,optional" validate:"omitempty,mongodb" comment:"库区"`   //库区Id
	WarehouseRackId string `form:"warehouse_rack_id,optional" validate:"omitempty,mongodb" comment:"货架"`   //货架Id
	Name            string `form:"name,optional" validate:"omitempty" comment:"货位名称"`                      //货位名称
	Code            string `form:"code,optional" validate:"omitempty" comment:"货位编号"`                      //货位编号：分配给客户的唯一标识符或编号，用于快速识别和检索客户信息
	Status          string `form:"status,optional" validate:"omitempty,oneof=激活 禁用 盘点中 关闭" comment:"货位状态"` //货位状态：不允许查询已删除的数据库
}

type WarehouseBinsResponse struct {
	Code int                  `json:"code"`
	Msg  string               `json:"msg"`
	Data WarehouseBinPaginate `json:"data"`
}

type WarehouseListRequest struct {
	Type   string `form:"type,optional" validate:"omitempty,oneof=分销中心 生产仓库 跨境仓库 电商仓库 冷链仓库 合规仓库 专用仓库 跨渠道仓库 自动化仓库 第三方物流仓库 " comment:"仓库类型"` //仓库类型
	Name   string `form:"name,optional" validate:"omitempty" comment:"仓库名称"`                                                               //仓库名称
	Code   string `form:"code,optional" validate:"omitempty" comment:"仓库编号"`                                                               //仓库编号：分配给客户的唯一标识符或编号，用于快速识别和检索客户信息
	Status string `form:"status,optional" validate:"omitempty,oneof=激活 禁用 盘点中 关闭" comment:"仓库状态"`                                          //仓库状态：不允许查询已删除的数据库
}

type WarehouseListResponse struct {
	Code int               `json:"code"`
	Msg  string            `json:"msg"`
	Data WarehousePaginate `json:"data"`
}

type WarehousePaginate struct {
	Total int64       `json:"total"`
	List  []Warehouse `json:"list"` //用户列表
}

type WarehouseRack struct {
	Id                string  `json:"id"`
	WarehouseId       string  `json:"warehouse_id,optional"`   //仓库Id
	WarehouseName     string  `json:"warehouse_name,optional"` //仓库名称
	WarehouseZoneId   string  `json:"warehouse_zone_id"`       //库区Id
	WarehouseZoneName string  `json:"warehouse_zone_name"`     //库区名称
	Type              string  `json:"type"`                    //货架类型
	Name              string  `json:"name"`                    //货架名称
	Code              string  `json:"code"`                    //货架编号：分配给客户的唯一标识符或编号，用于快速识别和检索客户信息
	Image             string  `json:"image"`                   // 货架图片
	Capacity          float64 `json:"capacity"`                // 货架容量
	CapacityUnit      string  `json:"capacity_unit"`           // 货架容量单位：面积、体积或其他度量单位
	Status            string  `json:"status"`                  //货架状态:激活 禁用 盘点中 关闭
	Manager           string  `json:"manager,optional"`        //负责人
	Contact           string  `json:"contact,optional"`        //联系方式
	Remark            string  `json:"remark"`                  //备注
	CreateBy          string  `json:"create_by,optional"`      //创建人
	CreatedAt         int64   `json:"created_at"`              //
	UpdatedAt         int64   `json:"updated_at"`              //
}

type WarehouseRackListRequest struct {
	WarehouseId     string `form:"warehouse_id,optional" validate:"omitempty,mongodb" comment:"仓库"`             //仓库Id
	WarehouseZoneId string `form:"warehouse_zone_id,optional" validate:"omitempty,mongodb" comment:"库区"`        //库区Id
	Type            string `form:"type,optional" validate:"omitempty,oneof=标准货架 重型货架 中型货架 轻型货架" comment:"货架类型"` //货架类型
	Name            string `form:"name,optional" validate:"omitempty" comment:"货架名称"`                           //货架名称
	Code            string `form:"code,optional" validate:"omitempty" comment:"货架编号"`                           //货架编号：分配给客户的唯一标识符或编号，用于快速识别和检索客户信息
	Status          string `form:"status,optional" validate:"omitempty,oneof=激活 禁用 盘点中 关闭" comment:"货架状态"`      //货架状态：不允许查询已删除的数据库
}

type WarehouseRackListResponse struct {
	Code int                   `json:"code"`
	Msg  string                `json:"msg"`
	Data WarehouseRackPaginate `json:"data"`
}

type WarehouseRackPaginate struct {
	Total int64           `json:"total"`
	List  []WarehouseRack `json:"list"` //用户列表
}

type WarehouseRackRequest struct {
	Id              string  `json:"id,optional" validate:"omitempty,mongodb" comment:"货架"`
	WarehouseZoneId string  `json:"warehouse_zone_id,optional" validate:"required,mongodb" comment:"库区"`
	Type            string  `json:"type,optional" validate:"required,oneof=标准货架 重型货架 中型货架 轻型货架" comment:"货架类型"` //货架类型
	Name            string  `json:"name,optional" validate:"required" comment:"货架名称"`                           //货架名称
	Code            string  `json:"code,optional" validate:"required" comment:"货架编号"`                           //货架编号：分配给客户的唯一标识符或编号，用于快速识别和检索客户信息
	Image           string  `json:"image,optional" validate:"required" comment:"货架图片"`                          //货架编号：分配给客户的唯一标识符或编号，用于快速识别和检索客户信息
	Capacity        float64 `json:"capacity,optional" validate:"omitempty,gte=0" comment:"货架容量"`                // 货架容量
	CapacityUnit    string  `json:"capacity_unit,optional" validate:"omitempty" comment:"货架容量单位"`               // 货架容量单位：面积、体积或其他度量单位
	Manager         string  `json:"manager,optional" validate:"omitempty" comment:"负责人"`                        //负责人
	Contact         string  `json:"contact,optional" validate:"omitempty,mobile" comment:"联系方式"`
	Remark          string  `json:"remark,optional" validate:"omitempty" comment:"备注"` //备注
}

type WarehouseRackStatusRequest struct {
	Id     string `json:"id" validate:"required" comment:"货架"`
	Status string `json:"status" validate:"required,oneof=激活 禁用 盘点中 关闭 删除" comment:"货架状态"` //货架状态
}

type WarehouseRacksRequest struct {
	Page            int64  `form:"page,optional" validate:"required,gte=1" comment:"页数""`
	Size            int64  `form:"size,optional" validate:"required,gte=5,lte=100" comment:"条数"`
	WarehouseId     string `form:"warehouse_id,optional" validate:"omitempty,mongodb" comment:"仓库"`             //仓库Id
	WarehouseZoneId string `form:"warehouse_zone_id,optional" validate:"omitempty,mongodb" comment:"库区"`        //库区Id
	Type            string `form:"type,optional" validate:"omitempty,oneof=标准货架 重型货架 中型货架 轻型货架" comment:"货架类型"` //货架类型
	Name            string `form:"name,optional" validate:"omitempty" comment:"货架名称"`                           //货架名称
	Code            string `form:"code,optional" validate:"omitempty" comment:"货架编号"`                           //货架编号：分配给客户的唯一标识符或编号，用于快速识别和检索客户信息
	Status          string `form:"status,optional" validate:"omitempty,oneof=激活 禁用 盘点中 关闭" comment:"货架状态"`      //货架状态：不允许查询已删除的数据库
}

type WarehouseRacksResponse struct {
	Code int                   `json:"code"`
	Msg  string                `json:"msg"`
	Data WarehouseRackPaginate `json:"data"`
}

type WarehouseRequest struct {
	Id           string  `json:"id,optional" validate:"omitempty,mongodb" comment:"仓库"`
	Type         string  `json:"type,optional" validate:"required,oneof=分销中心 生产仓库 跨境仓库 电商仓库 冷链仓库 合规仓库 专用仓库 跨渠道仓库 自动化仓库 第三方物流仓库 " comment:"仓库类型"` //仓库类型
	Name         string  `json:"name,optional" validate:"required" comment:"仓库名称"`                                                               //仓库名称
	Code         string  `json:"code,optional" validate:"required" comment:"仓库编号"`                                                               //仓库编号：分配给客户的唯一标识符或编号，用于快速识别和检索客户信息
	Image        string  `json:"image,optional" validate:"omitempty" comment:"图片"`                                                               //图片
	Address      string  `json:"address,optional" validate:"omitempty" comment:"仓库地址"`                                                           //仓库地址
	Capacity     float64 `json:"capacity,optional" validate:"omitempty,gte=0" comment:"仓库容量"`                                                    // 仓库容量
	CapacityUnit string  `json:"capacity_unit,optional" validate:"omitempty" comment:"仓库容量单位"`                                                   // 仓库容量单位：面积、体积或其他度量单位
	Manager      string  `json:"manager,optional" validate:"omitempty" comment:"负责人"`                                                            //负责人
	Contact      string  `json:"contact,optional" validate:"omitempty,mobile" comment:"联系方式"`                                                    //联系方式
	Remark       string  `json:"remark,optional" validate:"omitempty" comment:"备注"`                                                              //备注
}

type WarehouseStatusRequest struct {
	Id     string `json:"id" validate:"required" comment:"仓库"`
	Status string `json:"status" validate:"required,oneof=激活 禁用 盘点中 关闭 删除" comment:"仓库状态"` //仓库状态
}

type WarehouseTree struct {
	Id       string          `json:"id"`
	Name     string          `json:"name"`
	Children []WarehouseTree `json:"children"`
}

type WarehouseTreeResponse struct {
	Code int             `json:"code"`
	Msg  string          `json:"msg"`
	Data []WarehouseTree `json:"data"`
}

type WarehouseZone struct {
	Id            string  `json:"id,optional"`
	WarehouseId   string  `json:"warehouse_id,optional"`   //仓库Id
	WarehouseName string  `json:"warehouse_name,optional"` //仓库名称
	Name          string  `json:"name,optional"`           //库区名称
	Code          string  `json:"code,optional"`           //库区编号：分配给客户的唯一标识符或编号，用于快速识别和检索客户信息
	Image         string  `json:"image,optional"`          //库区图片
	Capacity      float64 `json:"capacity,optional"`       // 库区容量
	CapacityUnit  string  `json:"capacity_unit,optional"`  // 库区容量单位：面积、体积或其他度量单位
	Status        string  `json:"status,optional"`         //库区状态
	Manager       string  `json:"manager,optional"`        //负责人
	Contact       string  `json:"contact,optional"`        //联系方式
	Remark        string  `json:"remark,optional"`         //备注
	CreateBy      string  `json:"create_by,optional"`      //创建人
	CreatedAt     int64   `json:"created_at"`              //
	UpdatedAt     int64   `json:"updated_at"`              //
}

type WarehouseZoneListRequest struct {
	WarehouseId string `form:"warehouse_id,optional" validate:"omitempty,mongodb" comment:"仓库"`                                                //仓库Id
	Type        string `form:"type,optional" validate:"omitempty,oneof=分销中心 生产库区 跨境库区 电商库区 冷链库区 合规库区 专用库区 跨渠道库区 自动化库区 第三方物流库区" comment:"库区类型"` //库区类型
	Name        string `form:"name,optional" validate:"omitempty" comment:"库区名称"`                                                              //库区名称
	Code        string `form:"code,optional" validate:"omitempty" comment:"库区编号"`                                                              //库区编号：分配给客户的唯一标识符或编号，用于快速识别和检索客户信息
	Status      string `form:"status,optional" validate:"omitempty,oneof=激活 禁用 盘点中 关闭" comment:"库区状态"`                                         //库区状态：不允许查询已删除的数据库
}

type WarehouseZoneListResponse struct {
	Code int                   `json:"code"`
	Msg  string                `json:"msg"`
	Data WarehouseZonePaginate `json:"data"`
}

type WarehouseZonePaginate struct {
	Total int64           `json:"total"`
	List  []WarehouseZone `json:"list"` //库区列表
}

type WarehouseZoneRequest struct {
	Id           string  `json:"id,optional" validate:"omitempty,mongodb" comment:"库区"`
	WarehouseId  string  `json:"warehouse_id,optional" validate:"required,mongodb" comment:"仓库"`
	Name         string  `json:"name,optional" validate:"required" comment:"库区名称"`             //库区名称
	Code         string  `json:"code,optional" validate:"required" comment:"库区编号"`             //库区编号：分配给客户的唯一标识符或编号，用于快速识别和检索客户信息
	Image        string  `json:"image,optional" validate:"required" comment:"库区图片"`            //库区图片
	Capacity     float64 `json:"capacity,optional" validate:"omitempty,gte=0" comment:"库区容量"`  // 库区容量
	CapacityUnit string  `json:"capacity_unit,optional" validate:"omitempty" comment:"库区容量单位"` // 库区容量单位：面积、体积或其他度量单位
	Manager      string  `json:"manager,optional" validate:"omitempty" comment:"负责人"`          //负责人
	Contact      string  `json:"contact,optional" validate:"omitempty,mobile" comment:"联系方式"`  //联系方式
	Remark       string  `json:"remark,optional" validate:"omitempty" comment:"备注"`            //备注
}

type WarehouseZoneStatusRequest struct {
	Id     string `json:"id" validate:"required" comment:"库区"`
	Status string `json:"status" validate:"required,oneof=激活 禁用 盘点中 关闭 删除" comment:"库区状态"` //库区状态
}

type WarehouseZonesRequest struct {
	Page        int64  `form:"page,optional" validate:"required,gte=1" comment:"页数""`
	Size        int64  `form:"size,optional" validate:"required,gte=5,lte=100" comment:"条数"`
	WarehouseId string `form:"warehouse_id,optional" validate:"omitempty,mongodb" comment:"仓库"`                                                //仓库Id
	Type        string `form:"type,optional" validate:"omitempty,oneof=分销中心 生产库区 跨境库区 电商库区 冷链库区 合规库区 专用库区 跨渠道库区 自动化库区 第三方物流库区" comment:"库区类型"` //库区类型
	Name        string `form:"name,optional" validate:"omitempty" comment:"库区名称"`                                                              //库区名称
	Code        string `form:"code,optional" validate:"omitempty" comment:"库区编号"`                                                              //库区编号：分配给客户的唯一标识符或编号，用于快速识别和检索客户信息
	Status      string `form:"status,optional" validate:"omitempty,oneof=激活 禁用 盘点中 关闭" comment:"库区状态"`                                         //库区状态：不允许查询已删除的数据库
}

type WarehouseZonesResponse struct {
	Code int                   `json:"code"`
	Msg  string                `json:"msg"`
	Data WarehouseZonePaginate `json:"data"`
}

type WarehousesRequest struct {
	Page   int64  `form:"page,optional" validate:"required,gte=1" comment:"页数""`
	Size   int64  `form:"size,optional" validate:"required,gte=5,lte=100" comment:"条数"`
	Type   string `form:"type,optional" validate:"omitempty,oneof=分销中心 生产仓库 跨境仓库 电商仓库 冷链仓库 合规仓库 专用仓库 跨渠道仓库 自动化仓库 第三方物流仓库 " comment:"仓库类型"` //仓库类型
	Name   string `form:"name,optional" validate:"omitempty" comment:"仓库名称"`                                                               //仓库名称
	Code   string `form:"code,optional" validate:"omitempty" comment:"仓库编号"`                                                               //仓库编号：分配给客户的唯一标识符或编号，用于快速识别和检索客户信息
	Status string `form:"status,optional" validate:"omitempty,oneof=激活 禁用 盘点中 关闭" comment:"仓库状态"`                                          //仓库状态：不允许查询已删除的数据库
}

type WarehousesResponse struct {
	Code int               `json:"code"`
	Msg  string            `json:"msg"`
	Data WarehousePaginate `json:"data"`
}

type Warehousing struct {
	WarehouseId     string `json:"warehouse_id,optional"`      //仓库id
	WarehouseZoneId string `json:"warehouse_zone_id,optional"` //库区id
	WarehouseRackId string `json:"warehouse_rack_id,optional"` //货架id
	WarehouseBinId  string `json:"warehouse_bin_id,optional"`  //货位id
}
