// Code generated by goctl. DO NOT EDIT.

package model_mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	clientFieldNames          = builder.RawFieldNames(&Client{})
	clientRows                = strings.Join(clientFieldNames, ",")
	clientRowsExpectAutoSet   = strings.Join(stringx.Remove(clientFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	clientRowsWithPlaceHolder = strings.Join(stringx.Remove(clientFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheClientIdPrefix   = "cache:client:id:"
	cacheClientNamePrefix = "cache:client:name:"
)

type (
	clientModel interface {
		Insert(ctx context.Context, data *Client) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Client, error)
		FindByPage(ctx context.Context, query string) ([]Client, error)
		Count(ctx context.Context, query string) (int64, error)
		FindOneByName(ctx context.Context, name string) (*Client, error)
		Update(ctx context.Context, data *Client) error
		Delete(ctx context.Context, id int64) error
	}

	defaultClientModel struct {
		sqlc.CachedConn
		table string
	}

	Client struct {
		Id        int64     `db:"id"`
		Name      string    `db:"name"` // 客户名称
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newClientModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultClientModel {
	return &defaultClientModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`client`",
	}
}

func (m *defaultClientModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	clientIdKey := fmt.Sprintf("%s%v", cacheClientIdPrefix, id)
	clientNameKey := fmt.Sprintf("%s%v", cacheClientNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, clientIdKey, clientNameKey)
	return err
}

func (m *defaultClientModel) FindOne(ctx context.Context, id int64) (*Client, error) {
	clientIdKey := fmt.Sprintf("%s%v", cacheClientIdPrefix, id)
	var resp Client
	err := m.QueryRowCtx(ctx, &resp, clientIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", clientRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultClientModel) FindByPage(ctx context.Context, query string) ([]Client, error) {
	query = fmt.Sprintf("select %s from %s", clientRows, m.table) + query
	var resp []Client
	err := m.CachedConn.QueryRowsNoCacheCtx(ctx, &resp, query)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultClientModel) Count(ctx context.Context, query string) (int64, error) {
	query = fmt.Sprintf("select %s from %s", clientRows, m.table) + query
	var resp []Client
	err := m.CachedConn.QueryRowsNoCacheCtx(ctx, &resp, query)
	switch err {
	case nil:
		return int64(len(resp)), nil
	case sqlc.ErrNotFound:
		return 0, ErrNotFound
	default:
		return 0, err
	}
}

func (m *defaultClientModel) FindOneByName(ctx context.Context, name string) (*Client, error) {
	clientNameKey := fmt.Sprintf("%s%v", cacheClientNamePrefix, name)
	var resp Client
	err := m.QueryRowIndexCtx(ctx, &resp, clientNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", clientRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultClientModel) Insert(ctx context.Context, data *Client) (sql.Result, error) {
	clientIdKey := fmt.Sprintf("%s%v", cacheClientIdPrefix, data.Id)
	clientNameKey := fmt.Sprintf("%s%v", cacheClientNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?)", m.table, clientRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name)
	}, clientIdKey, clientNameKey)
	return ret, err
}

func (m *defaultClientModel) Update(ctx context.Context, newData *Client) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	clientIdKey := fmt.Sprintf("%s%v", cacheClientIdPrefix, data.Id)
	clientNameKey := fmt.Sprintf("%s%v", cacheClientNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, clientRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.Id)
	}, clientIdKey, clientNameKey)
	return err
}

func (m *defaultClientModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheClientIdPrefix, primary)
}

func (m *defaultClientModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", clientRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultClientModel) tableName() string {
	return m.table
}
