// Code generated by goctl. DO NOT EDIT.

package model_mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	stockOutDetailFieldNames          = builder.RawFieldNames(&StockOutDetail{})
	stockOutDetailRows                = strings.Join(stockOutDetailFieldNames, ",")
	stockOutDetailRowsExpectAutoSet   = strings.Join(stringx.Remove(stockOutDetailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	stockOutDetailRowsWithPlaceHolder = strings.Join(stringx.Remove(stockOutDetailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheStockOutDetailIdPrefix = "cache:stockOutDetail:id:"
)

type (
	stockOutDetailModel interface {
		Insert(ctx context.Context, data *StockOutDetail) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*StockOutDetail, error)
		FindByPage(ctx context.Context, query string) ([]StockOutDetail, error)
		Count(ctx context.Context, query string) (int64, error)
		Update(ctx context.Context, data *StockOutDetail) error
		Delete(ctx context.Context, id int64) error
	}

	defaultStockOutDetailModel struct {
		sqlc.CachedConn
		table string
	}

	StockOutDetail struct {
		Id           int64     `db:"id"`
		StockId      int64     `db:"stock_id"`      // 出库单id
		ProductId    int64     `db:"product_id"`    // 产品id
		ProductModel string    `db:"product_model"` // 产品型号
		ProductName  string    `db:"product_name"`  // 产品品名
		ProductSpecs string    `db:"product_specs"` // 产品规格
		Count        int64     `db:"count"`         // 产品数量（个、件）
		Price        float64   `db:"price"`         // 产品单价(厘/个)
		CreatedAt    time.Time `db:"created_at"`
		UpdatedAt    time.Time `db:"updated_at"`
	}
)

func newStockOutDetailModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultStockOutDetailModel {
	return &defaultStockOutDetailModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`stock_out_detail`",
	}
}

func (m *defaultStockOutDetailModel) Delete(ctx context.Context, id int64) error {
	stockOutDetailIdKey := fmt.Sprintf("%s%v", cacheStockOutDetailIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, stockOutDetailIdKey)
	return err
}

func (m *defaultStockOutDetailModel) FindOne(ctx context.Context, id int64) (*StockOutDetail, error) {
	stockOutDetailIdKey := fmt.Sprintf("%s%v", cacheStockOutDetailIdPrefix, id)
	var resp StockOutDetail
	err := m.QueryRowCtx(ctx, &resp, stockOutDetailIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", stockOutDetailRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStockOutDetailModel) FindByPage(ctx context.Context, query string) ([]StockOutDetail, error) {
	query = fmt.Sprintf("select %s from %s", stockOutDetailRows, m.table) + query
	var resp []StockOutDetail
	err := m.CachedConn.QueryRowsNoCacheCtx(ctx, &resp, query)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStockOutDetailModel) Count(ctx context.Context, query string) (int64, error) {
	query = fmt.Sprintf("select %s from %s", stockOutDetailRows, m.table) + query
	var resp []StockOutDetail
	err := m.CachedConn.QueryRowsNoCacheCtx(ctx, &resp, query)
	switch err {
	case nil:
		return int64(len(resp)), nil
	case sqlc.ErrNotFound:
		return 0, ErrNotFound
	default:
		return 0, err
	}
}

func (m *defaultStockOutDetailModel) Insert(ctx context.Context, data *StockOutDetail) (sql.Result, error) {
	stockOutDetailIdKey := fmt.Sprintf("%s%v", cacheStockOutDetailIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, stockOutDetailRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.StockId, data.ProductId, data.ProductModel, data.ProductName, data.ProductSpecs, data.Count, data.Price)
	}, stockOutDetailIdKey)
	return ret, err
}

func (m *defaultStockOutDetailModel) Update(ctx context.Context, data *StockOutDetail) error {
	stockOutDetailIdKey := fmt.Sprintf("%s%v", cacheStockOutDetailIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, stockOutDetailRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.StockId, data.ProductId, data.ProductModel, data.ProductName, data.ProductSpecs, data.Count, data.Price, data.Id)
	}, stockOutDetailIdKey)
	return err
}

func (m *defaultStockOutDetailModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheStockOutDetailIdPrefix, primary)
}

func (m *defaultStockOutDetailModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", stockOutDetailRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultStockOutDetailModel) tableName() string {
	return m.table
}
