// Code generated by goctl. DO NOT EDIT.

package model_mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	supplierFieldNames          = builder.RawFieldNames(&Supplier{})
	supplierRows                = strings.Join(supplierFieldNames, ",")
	supplierRowsExpectAutoSet   = strings.Join(stringx.Remove(supplierFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	supplierRowsWithPlaceHolder = strings.Join(stringx.Remove(supplierFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheSupplierIdPrefix   = "cache:supplier:id:"
	cacheSupplierNamePrefix = "cache:supplier:name:"
)

type (
	supplierModel interface {
		Insert(ctx context.Context, data *Supplier) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Supplier, error)
		FindByPage(ctx context.Context, query string) ([]Supplier, error)
		Count(ctx context.Context, query string) (int64, error)
		FindOneByName(ctx context.Context, name string) (*Supplier, error)
		Update(ctx context.Context, data *Supplier) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSupplierModel struct {
		sqlc.CachedConn
		table string
	}

	Supplier struct {
		Id        int64     `db:"id"`
		Name      string    `db:"name"` // 供货商名称
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newSupplierModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultSupplierModel {
	return &defaultSupplierModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`supplier`",
	}
}

func (m *defaultSupplierModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	supplierIdKey := fmt.Sprintf("%s%v", cacheSupplierIdPrefix, id)
	supplierNameKey := fmt.Sprintf("%s%v", cacheSupplierNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, supplierIdKey, supplierNameKey)
	return err
}

func (m *defaultSupplierModel) FindOne(ctx context.Context, id int64) (*Supplier, error) {
	supplierIdKey := fmt.Sprintf("%s%v", cacheSupplierIdPrefix, id)
	var resp Supplier
	err := m.QueryRowCtx(ctx, &resp, supplierIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", supplierRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSupplierModel) FindByPage(ctx context.Context, query string) ([]Supplier, error) {
	query = fmt.Sprintf("select %s from %s", supplierRows, m.table) + query
	var resp []Supplier
	err := m.CachedConn.QueryRowsNoCacheCtx(ctx, &resp, query)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSupplierModel) Count(ctx context.Context, query string) (int64, error) {
	query = fmt.Sprintf("select %s from %s", supplierRows, m.table) + query
	var resp []Supplier
	err := m.CachedConn.QueryRowsNoCacheCtx(ctx, &resp, query)
	switch err {
	case nil:
		return int64(len(resp)), nil
	case sqlc.ErrNotFound:
		return 0, ErrNotFound
	default:
		return 0, err
	}
}

func (m *defaultSupplierModel) FindOneByName(ctx context.Context, name string) (*Supplier, error) {
	supplierNameKey := fmt.Sprintf("%s%v", cacheSupplierNamePrefix, name)
	var resp Supplier
	err := m.QueryRowIndexCtx(ctx, &resp, supplierNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", supplierRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSupplierModel) Insert(ctx context.Context, data *Supplier) (sql.Result, error) {
	supplierIdKey := fmt.Sprintf("%s%v", cacheSupplierIdPrefix, data.Id)
	supplierNameKey := fmt.Sprintf("%s%v", cacheSupplierNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?)", m.table, supplierRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name)
	}, supplierIdKey, supplierNameKey)
	return ret, err
}

func (m *defaultSupplierModel) Update(ctx context.Context, newData *Supplier) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	supplierIdKey := fmt.Sprintf("%s%v", cacheSupplierIdPrefix, data.Id)
	supplierNameKey := fmt.Sprintf("%s%v", cacheSupplierNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, supplierRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.Id)
	}, supplierIdKey, supplierNameKey)
	return err
}

func (m *defaultSupplierModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheSupplierIdPrefix, primary)
}

func (m *defaultSupplierModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", supplierRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSupplierModel) tableName() string {
	return m.table
}
